### ISSUE TITLE
Can't push multi-refs to receiver without failing pre-receive hook

### ISSUE THREAD

**Issue by zubairov** [flynn/flynn#1000]
I tried using the ```gitreceived``` in our project, however run into the issues. Pushing simple one-commit repository to it worked ok, however when I have more complicated repository with multiple refs/branches then pre-receive hook is failing. Removing this line from the pre-recieve hook helps:

```
set -eo pipefail
```

helped, however it's not a good workaround as I could guess (I'm not a proficient in bash).

My question is what could potentially go wrong there and what is the best way to debug this issue?

Diff for my changes in ```gitreceived```:

```
index da8cc41..faccf4a 100644
--- a/gitreceived/gitreceived.go
+++ b/gitreceived/gitreceived.go
@@ -23,8 +23,10 @@ import (
 )

 const PrereceiveHookTmpl = `#!/bin/bash
-set -eo pipefail; while read oldrev newrev refname; do
-[[ $refname = "refs/heads/master" ]] && git archive $newrev | {{RECEIVER}} "$RECEIVE_REPO" "$newrev" | sed -$([[ $(uname) == "Darwin" ]] && echo l || echo u) "s/^/"$'\e[1G\e[K'"/"
+while read oldrev newrev refname; do
+  [[ "$refname" == "refs/heads/master" ]] && \
+    git archive "$newrev" | "{{RECEIVER}}" "$RECEIVE_REPO" "$newrev" "$RECEIVE_USER"
 done
 `
```

**Comment by titanous** [comment]
Can you provide an example git repo and push command that fails with an unmodified gitreceived?

**Comment by lmars** [comment]
@zubairov `gitreceived` is currently designed to only accept pushes of the master branch, this is what the following code enforces:

```
[[ $refname = "refs/heads/master" ]] && ...
```

So if that test fails, the script fails because `set -e` is used (which is short for `set -o errexit`, and exits the script if any command fails).

You can of course drop this test if you want to be able to push multiple branches, but the receiver script will not be aware of what branch is being pushed (as that information is not passed on to it), so I don't see what the benefit would be?
