### ISSUE TITLE
No packages for major distros

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#1036]
Following a chat with @lmars on IRC earlier this week, I thought it might be profitable to open an issue to discuss packaging for Flynn, specifically for Debian/Ubuntu (deb) and RHEL/Fedora (rpm).

I noticed that you previously provided deb packages, but now support only installation via a shell-based installer that uses the TUL. From my conversation with @lmars, it appears that you've gone for this route because:

* The one distribution system applies to all systems.
* Avoids re-downloading all files during an update.
* It's a secure system with reasonable usage.

As a sysadmin and a long-time personal Linux user (Fedora is my poison), I'd encourage you to consider providing packages for the system package managers of major distributions that you wish to target. I feel that this offers a number of advantages:

* Immediate familiarity to system administrators.
* Allows distribution-specific alterations (eg: upstart for Ubuntu, init.d for RHEL, systemd for Fedora) for a seamless out-of-box experience.
* Existing mechanisms for package signing.
* Existing mechanisms for package updating (both on an ad-hoc basis, and automated updating) and removal, eg: #1020.

Whilst @lmars did point out a number of barriers to this, such as large files that may stay the same between revisions, I am fairly certain that these issues are not entirely new ones, and that they can be resolved. Certainly both the Debian and RHEL package managers provide systems for package deltas, and packaging Flynn as multiple packages (eg: flynn-core, flynn-images) might also be a reasonable solution.

**Comment by thomasfedb** [comment]
I should note that, whilst I am unfamiliar with Flynn's internals, and don't (yet) write Go, I would be interested in being involved implementing this if it was considered a worthy end.

**Comment by titanous** [comment]
It's unlikely that we will support distro packaging. Here are some reasons:

1. Updates to Flynn need to be coordinated in a cluster-wide fashion to maintain
   availability, merely running `apt-get update` without coordination is not
   sufficient. In order to do this coordination with distro packages, we'd need
   to add a lot of awareness about the peculiarity of each distro to the updater
   systems.
1. Distro packaging and distribution tools are horrible. They are arcane,
   underdocumented, and really hard to work with. This is not a good experience
   for anyone involved, and multiplying this by every single packaging system
   and distro gets insane fast.
1. Having tooling for distro packaging encourages distro maintainers to package
   and distribute Flynn upstream. [We do](https://vagabond.github.io/rants/2013/06/21/z_packagers-dont-know-best/)
   [not](https://vagabond.github.io/rants/2013/06/21/zz_packaging-and-the-tide-of-history/)
   [want this](http://blog.lusis.org/blog/2013/09/23/stop-fighting-distros-part-2/).
1. The pinnacle of security for distro packaging is GPG signatures. This is
   pretty ridiculous. GPG doesn't use modern crypto, and there are [many more
   things to take into
   account](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt)
   than just making sure the bits are signed.
1. Container images don't fit well in distro packages for a variety of reasons.
   We never packaged them in the .deb, so we had to maintain a separate
   infrastructure anyway. Why bother with distro packaging when we can just
   utilize the same infrastructure and code to securely distributed everything?
1. Flynn hosts are really container hypervisors, so you shouldn't be running
   much other than Flynn on the host OS. This mitigates many complaints, valid
   or not, about not playing nice with other things on the system.

And now I'll address some of your points directly:

> Immediate familiarity to system administrators.

This is the primary thing we lose. It's basically the same as that thing you wanted to install that was too new, so you had to `make install` it. Also, as soon as we start dealing with container images and cluster-wide upgrades, it becomes unfamiliar fast. We can't do much about this other than work to make it as invisible and painless as possible.

> Allows distribution-specific alterations (eg: upstart for Ubuntu, init.d for RHEL, systemd for Fedora) for a seamless out-of-box experience.

We can do these distro-specific alterations in our install script, it's the same amount of work from our perspective.

> Existing mechanisms for package signing.

As mentioned above, this amounts to adding a GPG signature, which is not a very high bar. TUF goes much further.

> Existing mechanisms for package updating (both on an ad-hoc basis, and automated updating) and removal.

Updating is more complex, as mentioned. We can sort out cleanup pretty easily.
