### ISSUE TITLE
flynn-host doesn't kill everything before it shuts down

### ISSUE THREAD

**Issue by bgentry** [flynn/flynn#1177]
From @titanous:

```
titanous: bgentry: the root cause of all of those issues is flynn-host not everything before it shuts down, please file an issue so that I don't forget to look into it
titanous: workaround is to `sudo killall .containerinit`
```

This causes errors when trying to re-run integration tests locally, indicated by the following logs:

```
removing volume id="c092ffcc4a6342d6bd96afa8290323d3"... t=2015-03-06T00:34:38+0000 lvl=dbug msg="zfs destroy -f flynn-default/c092ffcc4a6342d6bd96afa8290323d3" package=zfs
t=2015-03-06T00:34:39+0000 lvl=dbug msg="zfs destroy -f flynn-default/c092ffcc4a6342d6bd96afa8290323d3" package=zfs
t=2015-03-06T00:34:40+0000 lvl=dbug msg="zfs destroy -f flynn-default/c092ffcc4a6342d6bd96afa8290323d3" package=zfs
t=2015-03-06T00:34:41+0000 lvl=dbug msg="zfs destroy -f flynn-default/c092ffcc4a6342d6bd96afa8290323d3" package=zfs
t=2015-03-06T00:34:42+0000 lvl=dbug msg="zfs destroy -f flynn-default/c092ffcc4a6342d6bd96afa8290323d3" package=zfs
t=2015-03-06T00:34:43+0000 lvl=dbug msg="zfs destroy -f flynn-default/c092ffcc4a6342d6bd96afa8290323d3" package=zfs
error: exit status 1: "/sbin/zfs zfs destroy -f flynn-default/c092ffcc4a6342d6bd96afa8290323d3" => cannot destroy 'flynn-default/c092ffcc4a6342d6bd96afa8290323d3': dataset is busy

some volumes were not destroyed successfully
state db file "/var/lib/flynn/volumes/volumes.bolt" removed.
Bootstrap failed
```

**Comment by bgentry** [comment]
I also had to `killall postgres` this last time to get rid of the same error message.

**Comment by bgentry** [comment]
Even when I've killed all processes I can see that would cause this issue, I can still get errors. Waiting a little while and trying again seems to make them go away without doing anything further =/

**Comment by heavenlyhash** [comment]
I added a retry to volume deletion to try to attempt compensate for this symptom (but I don't know what the root cause is): https://github.com/flynn/flynn/blob/4ed91f45a0952dabcdd478cde61faa0ff912b4c2/host/volume/zfs/zfs.go#L182  Maybe it should be increased.

https://github.com/zfsonlinux/zfs/issues/1810 might be related.

**Comment by titanous** [comment]
@benburkert

I believe this issue is caused by logmux. First, during shutdown `mux.Close` is called before `backend.Cleanup`, so it just hangs waiting for producers to finish that never do and blocks subsequent shutdown actions. Second, after fixing that, and all of the containers have been killed by cleanup, all of the logmux follower goroutines are still around:

```text
goroutine 227 [semacquire, 1 minutes]:
sync.(*Cond).Wait(0xc20817f0b0)
	/usr/local/go/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc20817f080, 0xc2081c9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0xc208480680, 0xc2081c9000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:134 +0x5b
bufio.(*Reader).fill(0xc208430cc0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208430cc0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc208430cc0, 0x0, 0x0, 0x0, 0xc208303900, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
github.com/flynn/flynn/host/logmux.(*LogMux).follow(0xc2080591d0, 0x7f68fa2f24f8, 0xc208480680, 0xc2083590e0)
	/home/vagrant/go/src/github.com/flynn/flynn/host/logmux/logmux.go:127 +0x15e
created by github.com/flynn/flynn/host/logmux.(*LogMux).Follow
	/home/vagrant/go/src/github.com/flynn/flynn/host/logmux/logmux.go:117 +0x318
```

To replicate my results, run `bootstrap-flynn`, tail `/tmp/flynn-host.log`, and kill the flynn-host process. Note that it hangs. Send a `SIGQUIT` to the process and note that the shutdown is hanging on the logmux close.

Add this patch:

```diff
diff --git a/host/host.go b/host/host.go
index 10ce72c..5f9f276 100644
--- a/host/host.go
+++ b/host/host.go
@@ -186,6 +186,7 @@ func runDaemon(args *docopt.Args) {
        }

        mux := logmux.New(1000)
+       shutdown.BeforeExit(func() { mux.Close() })

        switch backendName {
        case "libvirt-lxc":
@@ -279,7 +280,6 @@ func runDaemon(args *docopt.Args) {
        if err := mux.Connect(disc, "flynn-logaggregator-syslog"); err != nil {
                shutdown.Fatal(err)
        }
-       shutdown.BeforeExit(func() { mux.Close() })

        cluster, err := cluster.NewClient()
        if err != nil {
```

Repeat the same steps and note that the containers are killed, but the process still hangs after shutting them down.

**Comment by titanous** [comment]
Separately, the ZFS issues and running container processes are a red herring. The `kill-flynn` script terminates flynn-host uncleanly if it times out, and since it's hanging it does this 100% of the time on the current master. I think the bind mounts don't get cleaned up, causing the ZFS issues.

**Comment by lmars** [comment]
This is preventing job resurrection from working because the state never gets saved on reboot.
