### ISSUE TITLE
BitBucket OAuth support?

### ISSUE THREAD

**Issue by stela5** [flynn/flynn#1207]
I see you integrate with GitHub OAuth for application deployment.  Any plans to support BitBucket?  https://confluence.atlassian.com/display/BITBUCKET/OAuth+on+Bitbucket

**Comment by titanous** [comment]
We currently have no plans to implement Bitbucket support, future features are prioritized based on user requests, so comment here if you'd use this.

**Comment by swistaczek** [comment]
@titanous hi, in 1-10 scale how hard it would be to extend flynn for BitBucket support? I would like to help with this feature :).

**Comment by titanous** [comment]
@swistaczek Thanks for your interest! It looks like this would require refactoring or duplicating a bunch of views and will double the test/QA complexity. At this point we're going to wait until we have full integration test coverage for the existing dashboard features before adding more complexity, as it would otherwise require manual testing.

**Comment by cdesch** [comment]
@titanous can this issue be revisited at this point in time? I would be willing to pair up with @swistaczek to implement some of the oauth aspects to support bitbucket.

**Comment by titanous** [comment]
@cdesch We currently don't have the bandwidth to maintain this feature in the dashboard. I think the next closest thing we will be doing is adding support for pulling from other git repos (including BitBucket) in the dashboard.
