### ISSUE TITLE
Deploy docker-compose.yml

### ISSUE THREAD

**Issue by geovanisouza92** [flynn/flynn#1361]
There are plans to support deploy from docker-compose.yml?

I think that this could be added on ```flynn release add``` command. Maybe one ```flynn release compose -f [ fig | docker-compose ].yml```

**Comment by lmars** [comment]
@geovanisouza92 it is doubtful we will support `docker-compose.yml` because it contains keys which are either not supported, or not necessary in Flynn.

For example the `build` key is unsupported because Flynn does not build images using Dockerfiles at runtime, and `links` / `expose` are not necessary because each job has a cluster routable IP address and can be looked up in service discovery via DNS / HTTP.

Our plan is to have a `Flynnfile` which will serve a similar use case as `docker-compose.yml`, but support things like depending on Flynn appliances (e.g. PostgreSQL / Redis etc.), configuring service health checks, specifying build / deploy hooks etc. (see #1084).
