### ISSUE TITLE
when flynn-host bootstrap error: "run-app postgres error: cluster: no servers found"

### ISSUE THREAD

**Issue by tjudream** [flynn/flynn#1381]
I install flynn cluster in three ubuntu-14.04 amd64
when I exec "sudo \
    CLUSTER_DOMAIN=demo.localflynn.com \
    flynn-host bootstrap --min-hosts=3 /etc/flynn/bootstrap-manifest.json"
There is error.
check online-hosts
require-env require-env
gen-random pg-password
gen-random pg-password xxxx
run-app postgres
run-app postgres error: cluster: no servers found

Why? Thanks!

**Comment by titanous** [comment]
Please run `flynn-host collect-debug-info` and post the gist link.

**Comment by tjudream** [comment]
Thanks. Today this problem is not occured, after I restart three vms(created by VMware vSphere).
But another problem happened.
When I exec "wait postgres-wait error: bootstrap: timed out waiting for http://postgres-api.discoverd/ping, last response 'Get http://postgres-api.discoverd/ping: dial tcp: lookup postgres-api.discoverd: no such host' ".
And my local network cannot connect gist.github.com for some reason.
My flynn-host version is v20150328.0.
In my syslog, there are some warnings:
"RecordRoutingInof: Unable to collect IPv4 routing table."
"Failed to get nic info."

**Comment by lmars** [comment]
@tjudream your cluster is probably in a broken state, you should do a clean install of Flynn on all nodes by running the following:

```
$ curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn
$ sudo bash /tmp/install-flynn --clean
```

You should then start `flynn-host` on all nodes and re-run the bootstrap command.

If you are still having issues, you can create a tarball of logs rather than uploading to a gist by running:

```
sudo flynn-host collect-debug-info --tarball
```

then post the tarball somewhere for us to download and take a look at.

**Comment by tjudream** [comment]
Thank you very much！
It works！
