### ISSUE TITLE
Rollback failed deploys does not work

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#1409]
1. Create an app
2. Push it to flynn
3. Introduce an error in your app which make it fail to startup, a syntax error will do just fine.
4. Push the updated app to flynn, watch it fail to boot.

Flynn keeps trying to boot the app.

**If** the expected behavior is to rollback to the last good app version it does not work as expected.

**Comment by lmars** [comment]
@kwando by default, the deployer uses job events to determine whether a job has started correctly, which means as long as the job transitions to the `up` state the deployment will not fail, regardless of whether the job subsequently crashes (in which case the scheduler will try to restart the crashed job).

The fix for this is for your app to register a service with a health check and indicate to the deployer that it should use service events rather than job events, so that a job is only considered up once it is correctly servicing requests. The low-level tools are in place for this to happen, we just need to expose this to the end-user, which we plan to do when implementing the `Flynnfile` (see #1084).

**Comment by kwando** [comment]
Yeah, I kind of suspected this would be the case. Thanks for this clarification!

**Comment by titanous** [comment]
Closing, as this looks like it's working as expected currently.
