### ISSUE TITLE
Router sticky sync failure

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1425]
The streaming router state sync does not appear to get the sticky flag when creating a new route.

**Reproduction**

1. Deploy an app.
1. Create a new route using this command: `flynn route add http --sticky sticky-test.dev.localflynn.com` (using the CLI from master, due to #1420)
1. Curl the route and note that there is no `Set-Cookie` header with a `_backend` cookie as expected.
1. Restart the router by killing it, curl again, note that the header is set.

**Comment by benburkert** [comment]
I believe this is due to the router internally setting "sticky" on the proxy transport. There is one transport per backend service, so if a non-sticky route is added before a sticky one to the same service, both routes will be non-sticky: https://github.com/flynn/flynn/blob/master/router/http.go#L225

Unfortunately, this is not an easy fix b/c this area of the router very convoluted and complex. A while ago we started refactoring this stuff [here](https://github.com/benburkert/flynn/tree/router-route-table), but put it aside. I think we should fix this after landing that refactor.

**Comment by josephglanville** [comment]
I just bumped into this when trying to add update support for leader routing, which has the same problem.  You currently can't have 2 routes to the same service with different proxy/transport level settings.
