### ISSUE TITLE
Installation on coreOs

### ISSUE THREAD

**Issue by keyscores** [flynn/flynn#1513]
Installing Flynn on coreOS ends in permissions error.

core@flynn ~ $ L=/usr/local/bin/flynn && curl -sL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
-bash: /usr/local/bin/flynn: Read-only file system

**Comment by lmars** [comment]
From the command you are trying to run, it looks like you are trying to install the Flynn CLI (rather than installing a Flynn cluster), is this intentional?

If you do intend to use the Flynn CLI on a CoreOS machine, I would suggest either downloading the binary to a location you have read-write permissions to (e.g. `L=$HOME/bin/flynn ...`) or building a Docker image with the Flynn CLI in it and running that.

If your intention was to actually run a Flynn cluster on CoreOS, this is not currently supported, we currently only support Ubuntu 14.04.

**Comment by robert-zaremba** [comment]
Is there a tutorial how to run a flynn on a coreOS cluster?
