### ISSUE TITLE
Proxy EC2 metadata service, for per-container IAM roles

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#1534]
https://github.com/dump247/docker-ec2-metadata provides a good example of how to accomplish this for Docker; it sounds like a few tweaks ("change `docker0` to `flynnbr0`" per @lmars) would make this viable for Flynn.

This would allow for least-privilege security on containers, and feature parity with EC2 Container Service.

(Some thought would also need to be put to how one connects a role to an app. I presume the IAM_ROLE environmental variable is at the Docker layer, and wouldn't automatically come in from `flynn env`.)

**Comment by lmars** [comment]
A possible approach:

* Run the ec2-metadata service in Flynn with both [HostNetwork](https://github.com/flynn/flynn/blob/master/controller/types/types.go#L51) (so that it can bind to a well known port on the host, say `18000`) and [Omni](https://github.com/flynn/flynn/blob/master/controller/types/types.go#L50) (present on all hosts) set to true
* Add iptables rules to all hosts to forward packets destined for `169.254.169.254:80` to the ec2-metadata service (e.g. `$EXTERNAL_IP:18000`)
* Have the ec2-metadata service subscribe to job events and maintain a mapping of job IP address to IAM role (the role for example being stored in the app, release or job metadata)

**Comment by temujin9** [comment]
Okay, this one has bumped up in priority internally. You make it sounds simple, so I'll take a stab at it soon.

**Comment by dump247** [comment]
@lmars Is there a flynn golang sdk? How would I connect to the local flynn host (is there a consistent hostname)?

**Comment by lmars** [comment]
@dump247 we have a VirtualBox image that we use for local development, see the [Flynn development guide](https://flynn.io/docs/development).

**Comment by temujin9** [comment]
He's talking about connecting to the flynn cluster that the app is running
on.

Cheers,

--
Nathaniel Eliot
T9 Productions

**Comment by lmars** [comment]
@temujin9 ah ok, I misunderstood.

@dump247 you can access the `flynn-host` HTTP service at `127.0.0.1:1113` ([here are the routes](https://github.com/flynn/flynn/blob/master/host/http.go#L470-L482) and [here is a client](https://github.com/flynn/flynn/blob/master/pkg/cluster/host.go)).

You can also look up the address of the `flynn-host` service in discoverd by issuing a GET request to `http://127.0.0.1:1111/services/flynn-host/instances`

**Comment by dump247** [comment]
@lmars how do you set HostNetwork and Omni to true?

**Comment by temujin9** [comment]
@dump247 using https://github.com/flynn/flynn/pull/2377, these are each properties to set per-process.

**Comment by temujin9** [comment]
See https://github.com/flynn/flynn/blob/master/controller/types/types.go#L42-L62 for details.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
