### ISSUE TITLE
Install from source without external auto-update?

### ISSUE THREAD

**Issue by GothAck** [flynn/flynn#1657]
I'm uncomfortable with a service running as root auto updating from a third party source, via an unknown path (not an apt repo). Is there any method to install and update flynn from source? Or to build debian packages myself?

**Comment by titanous** [comment]
The only thing that auto-updates currently is the `flynn` command-line tool (it securely checks for updates only when used and a maximum of once every twelve hours). The updater for Flynn clusters is not complete and will not initially auto-update.

The update system we use, [The Update Framework](http://theupdateframework.com/), is more secure than an apt repo.

You are always free to build and run Flynn yourself (you can even run your own update repo), the instructions are available here: https://flynn.io/docs/development

**Comment by GothAck** [comment]
Huh, so it's "The Update Framework" or nothing? I'd rather trust my already secured apt repo...

**Comment by lmars** [comment]
@GothAck one issue with debian packaging is that it isn't really a good fit for doing co-ordinated, reliable, cluster wide updates, and there are [a few attack scenarios](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L124-L158) which The Update Framework protects against which apt repos do not.

Because Flynn can be considered as a cluster-aware container hypervisor running a variety of built-in components, doing reliable updates is not as simple as `apt-get update; apt-get install flynn-host`. As an example, updating the built-in PostgreSQL cluster involves pulling the correct image on all hosts, then doing a one-by-one deployment of each node, checking that data is correctly replicated at each stage to maintain data integrity.

There are also some other points raised in [this issue](https://github.com/flynn/flynn/issues/1036) which are relevant.
