### ISSUE TITLE
When updating I get the error "pg cluster in unhealthy state"

### ISSUE THREAD

**Issue by b3njamin** [flynn/flynn#1661]
pg cluster in unhealthy state (too few syncs)

https://gist.github.com/3266345d084810a50b51

**Comment by titanous** [comment]
@lmars This appears to be the failed postgres deploy log: https://gist.githubusercontent.com/anonymous/3266345d084810a50b51/raw/c329590fb3106a722a8c7d908f18bc7bfdaf9ec0/controller-worker-flynn1-b4e72b755b3e41879a24b00bdbef943a.log

**Comment by b3njamin** [comment]
Looking into it further when I updated via `flynn-host  update` the postgres app came back with "timed out waiting for deployment completion". Could be related to #1659?

**Comment by lmars** [comment]
So the postgres deployment completed, but the job didn't get deleted as the acquired pg connection was dead:

```
t=2015-07-08T09:46:37+0000 lvl=info msg="deployment complete" app=worker fn=HandleDeployment deployment_id=44629b9746ee4985acfd6c9a895d3e8b app_id=d29c49527e1546a4b2b8331a927afd24 strategy=postgres
t=2015-07-08T09:46:37+0000 lvl=info msg="marking the deployment as done" app=worker fn=HandleDeployment deployment_id=44629b9746ee4985acfd6c9a895d3e8b app_id=d29c49527e1546a4b2b8331a927afd24 strategy=postgres
t=2015-07-08T09:46:37+0000 lvl=info msg="received deployment event" app=worker fn=HandleDeployment deployment_id=44629b9746ee4985acfd6c9a895d3e8b app_id=d29c49527e1546a4b2b8331a927afd24 strategy=postgres status=complete type= state=
2015/07/08 09:46:37 attempting to delete job 10: conn is dead
2015/07/08 09:46:37 event=job_worked job_id=10 job_type=deployment
```

This lead to another worker picking up the job, and then failing due to the state not being as expected.

We need to fix two things:

* acquire a new connection if we get a `conn is dead` error after deploying postgres
* don't fail a postgres deployment if the deployment has actually already happened (i.e. there are the correct number of new release jobs)
