### ISSUE TITLE
stoping flynn-host with upstart takes long time

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#1679]
```sudo stop flynn-host``` returns before flynn-host is stopped. When it returns I can still visit http://my-app.demo.localflynn.com though it responds with a 500 "Service Unavailable".

**Comment by lmars** [comment]
I believe the issue here is that `flynn-host` stops all the jobs (including discoverd), but then subsequently tries to [unregister it's service](https://github.com/flynn/flynn/blob/master/host/discoverd.go#L22) which blocks for 30s (as we [use a retry dialer](https://github.com/flynn/flynn/blob/master/discoverd/client/client.go#L51)).

We should shuffle the shutdown hooks so that the service unregister happens before stopping the jobs.

**Comment by lmars** [comment]
Oh, also your router remains active (albeit serving 503s) because the router suffers the same fate, it gets stuck at shutdown trying to unregister it's service because flynn-host (potentially) stops discoverd before the router.
