### ISSUE TITLE
Deploying Wordpress 

### ISSUE THREAD

**Issue by dnbert** [flynn/flynn#1681]
How does Flynn manage stateful applications like Wordpress that rely on local data storage for plugins/caches/uploads? What process, if any, does Flynn use to help keep that data in sync?

**Comment by lmars** [comment]
Flynn currently supports adding ZFS volumes to your applications which means data saved to the volume will be persisted even if the job dies, but these volumes are not currently sticky, so whilst the data remains on disk, restarting your app will get a new, empty volume. This will be fixed by our [v2 scheduler](https://github.com/flynn/flynn/issues/1484).

As for keeping data in sync between multiple jobs, it is not currently supported out of the box but we have an issue tracking [adding NFS support](https://github.com/flynn/flynn/issues/1521).
