### ISSUE TITLE
"Timed out waiting for deployment completion" errors

### ISSUE THREAD

**Issue by tianx2** [flynn/flynn#1682]
It appears that after some deployments, I started to get some "timed out waiting for deployment completion" errors. Not sure if it's related to the other ones that have been reported.

https://gist.github.com/anonymous/3eab90a37ba002d920bd
https://gist.github.com/anonymous/d3c09352564b3b481e2c

Any help will be appreciated. It seems there are long periods where there are timeouts in `etcd`. Also there seems to be issues in `discoverd`.

```
501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

**Comment by titanous** [comment]
I'm looking at this now. The etcd failures were reported upstream at coreos/etcd#2791 with no resolution, but I'm not sure that this is the cause of the deploy failures.

**Comment by lmars** [comment]
@tianx2 please gist the output of the following (a list of all your app's formations):

```
flynn -a controller pg psql -- -c "SELECT * FROM formations WHERE app_id = '67c14ade-3181-4984-9927-7a97a001932a'"
```

**Comment by tianx2** [comment]
@lmars 

https://gist.github.com/tianx2/2b226826d789aa3df779

**Comment by titanous** [comment]
@tianx2 Just to clarify, it looks like you have provided log dumps for two single-node clusters, we have been looking at `ip-10-100-60-101`. Which cluster did you run that command against?

**Comment by tianx2** [comment]
@titanous I just realized that and I updated the gist.

https://gist.github.com/tianx2/2b226826d789aa3df779

**Comment by lmars** [comment]
@tianx2 so it seems your scheduler has stopped functioning correctly. We are in the process of implementing a new scheduler (#1484), and this particular issue will be fixed once that lands (as it will have an anti-entropy routine to keep in sync with the cluster).

In the meantime, I recommend restarting your scheduler and then retrying your deployment. Since you are running a single node cluster, and it is the scheduler's job to restart jobs, if you just kill it it will not be restarted, so instead you will need to manually boot a second scheduler, kill the first one, then kill the manual one once it has started another scheduler (**NOTE** if this fails then your cluster will likely be unrecoverable, use `flynn export` to backup your app first to avoid data loss):

```
# run a manual scheduler (it will have type "run" in "flynn ps")
$ MANUAL_ID=$(flynn -a controller run -d scheduler)

# check the job with id $MANUAL_ID is running, and grab the id of
# the job with type "scheduler" into $OLD_ID
$ flynn -a controller ps

# kill the old scheduler
$ flynn -a controller kill $OLD_ID

# check a new job with type "scheduler" is now running
$ flynn -a controller ps

# kill the manual scheduler
$ flynn -a controller kill $MANUAL_ID
```

You should now have a functioning scheduler, and be able to do a deployment.

If you have any trouble, or you want clarification on these steps, feel free to join us in IRC (Freenode #flynn).

**Comment by tianx2** [comment]
Thanks @lmars! I will probably run these steps tomorrow. I will let you know how it goes. I'll hop into the IRC channel if I have any questions.

**Comment by tianx2** [comment]
Thanks again @titanous @lmars for the support. The issue seems to be resolved now.

**Comment by titanous** [comment]
The first step needs to be updated to this:

```text
MANUAL_ID=$(flynn -a controller run -d -e sh -- -c "PORT=5000 /bin/start-flynn-controller scheduler")
```
