### ISSUE TITLE
Getting "Authenication required" on first push to cluster

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#1820]
Getting this when pushing the first app to new cluster.
```
$ git push flynn master
remote: Authentication required
fatal: Authentication failed for 'https://<cluster domain>/pigeons-curse-harty.git/'
```

It works if I try to push again.
Note: I have not downloaded the CA-file if that makes any difference.

**Comment by titanous** [comment]
What git version are you using? Please post the output of a failing push with `GIT_TRACE=1` set.

**Comment by kwando** [comment]
```
$ GIT_TRACE=1 git push flynn master                                                                                         
13:46:11.181848 git.c:346               trace: built-in: git 'push' 'flynn' 'master'
13:46:11.183214 run-command.c:351       trace: run_command: 'git-remote-https' 'flynn' 'https://git.<cluster domain>/zebras-invite-gore.git'
13:46:12.746628 run-command.c:351       trace: run_command: 'git credential-osxkeychain get'
13:46:12.747378 run-command.c:199       trace: exec: '/bin/sh' '-c' 'git credential-osxkeychain get' 'git credential-osxkeychain get'
13:46:12.750910 git.c:555               trace: exec: 'git-credential-osxkeychain' 'get'
13:46:12.751460 run-command.c:351       trace: run_command: 'git-credential-osxkeychain' 'get'
13:46:14.273043 run-command.c:351       trace: run_command: 'git credential-osxkeychain erase'
13:46:14.273848 run-command.c:199       trace: exec: '/bin/sh' '-c' 'git credential-osxkeychain erase' 'git credential-osxkeychain erase'
13:46:14.276977 git.c:555               trace: exec: 'git-credential-osxkeychain' 'erase'
13:46:14.277588 run-command.c:351       trace: run_command: 'git-credential-osxkeychain' 'erase'
13:46:14.307501 run-command.c:351       trace: run_command: '/usr/local/bin/flynn git-credentials erase'
13:46:14.308195 run-command.c:199       trace: exec: '/bin/sh' '-c' '/usr/local/bin/flynn git-credentials erase' '/usr/local/bin/flynn git-credentials erase'
remote: Authentication required
fatal: Authentication failed for 'https://git.<cluster domain>/zebras-invite-gore.git/'

kwando at alice in ~/<project path> on master
```
```
$ git --version                                                                                                                                                                                                      
git version 2.3.2 (Apple Git-55)
```

**Comment by titanous** [comment]
I have successfully replicated the issue with the stock git on OS X:

1. Install the `git-credential-osxkeychain` helper.
1. Enable the helper with `git config --global credential.helper osxkeychain`
1. Bootstrap and configure a development cluster and do a git push.
1. The push is successful. During the push, no credential is available from `osxkeychain` and is correctly read from our `flynn` credential helper and stored into the keychain by the `osxkeychain` helper.
1. Re-bootstrap a cluster at the same URL, creating a new, different password and do a git push.
1. The old password is read from the keychain by `osxkeychain` and the result is a 401 error.
1. The old credential is erased from the helpers.
1. The subsequent push succeeds as the old credential is no long available from `osxkeychain` and the process repeats from step 4.

I have been unable to replicate this issue with git v2.5.1 from Homebrew.

Since this issue is specific to those who are using stock git, have a third-party credential helper installed, *and* have re-bootstrapped with the same URL and a different key I don't think we need to do anything about this since it resolves itself after another push. If anyone finds a config flag or response code that solves this issue, I'd be happy to accept a PR. It doesn't seem like any more effort is warranted to investigate non-workaround solutions to this.

**Comment by alfredqy** [comment]
I've got the following. This is a cluster my team created and I grabbed the info from ~/.flynnrc. Anything I was missing there? Thanks!

$ GIT_TRACE=1 git push flynn master
23:44:38.348416 git.c:350               trace: built-in: git 'push' 'flynn' 'master'
23:44:38.358447 run-command.c:336       trace: run_command: 'git-remote-https' 'flynn' 'https://git.qgg4.flynnhub.com/catch.git'
23:44:38.916757 run-command.c:336       trace: run_command: 'git credential-osxkeychain get'
23:44:38.921633 run-command.c:195       trace: exec: '/bin/sh' '-c' 'git credential-osxkeychain get' 'git credential-osxkeychain get'
23:44:38.944360 git.c:563               trace: exec: 'git-credential-osxkeychain' 'get'
23:44:38.945144 run-command.c:336       trace: run_command: 'git-credential-osxkeychain' 'get'

**Comment by titanous** [comment]
@alfredqy Did you run `flynn cluster add` using the details or copy the `.flynnrc` file over?

**Comment by alfredqy** [comment]
I copied the rc file over. What are the proper steps to set up multiple
people to have access to a cluster?

**Comment by titanous** [comment]
You should run `flynn cluster add` with the details from the file. It will handle setting up git credentials and the CA certificate.
