### ISSUE TITLE
Environment variables not retained across deploys

### ISSUE THREAD

**Issue by nobert** [flynn/flynn#1885]
Browser: Chrome stable
OS: OS X 10.10.5

Environment variables are not persisting across deploys. Tested on dev vagrant and an AWS cluster.

1. Set environment variables, e.g. `flynn -a app env set a=b`
2. Deploy a new revision via dashboard.
3. sad :(

**Comment by titanous** [comment]
I believe the `flynn release add` case is (somewhat) intentional as it just pipes the full release JSON in which will replace the previous release. Environment variables are contained in the immutable release, `flynn env set` creates a new release based on the current one with updated variables.

The dashboard issue should be investigated ASAP by @jvatic.
