### ISSUE TITLE
Cannot access dashboard, cert is not trusted

### ISSUE THREAD

**Issue by tuananh** [flynn/flynn#1890]
I follow the instruction and set the cert to `Always Trust`, though i still got stuck at the dashboard.

![](https://dl.dropboxusercontent.com/s/azl6soj5xgob7nu/2015-09-19%20at%207.50%20AM.png)

**Comment by jvatic** [comment]
@tuananh what browser/version are you using? Does restarting the browser work around the issue?

**Comment by tuananh** [comment]
I'm using chrome dev latest. Also tested with Safari stable. Tried restarting browser and my machine too wouldnt help it



--
Tuan Anh Tran

**Comment by jvatic** [comment]
Just to confirm, it's the certificate installation page you're stuck on? Please try it in Firefox if you can as it uses it's own database so that can narrow down the issue. Any errors you can post from the JavaScript console (including network requests) would be helpful, as well as the version of Flynn you're running (output of `flynn-host version` from within any nodes in the cluster).

**Comment by tuananh** [comment]
Output of flynn-host version is `v20150918.0`

With Firefox, I'm getting 

![](https://dl.dropboxusercontent.com/s/s0au2mqj40wh8fs/2015-09-19%20at%2011.33%20PM.png)

![](https://dl.dropboxusercontent.com/s/81p3y1aw4itp4oq/2015-09-19%20at%2011.34%20PM.png)

**Comment by tuananh** [comment]
Turns out the port 443 was not opened on the server. Totally my fault.

**Comment by jvatic** [comment]
Glad you got it sorted out, and thanks for reporting the issue!
