### ISSUE TITLE
discoverd raft "timed out enqueuing operation"

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#1899]
I deleted and recreated the 'terminus' app, and an old container stuck around running, which was preventing a new container from spawning. Terminating the container let the new one start fine.

https://gist.github.com/e376d4894c149da5f3b5 has the debug-info, prior to terminating the errant container.

**Comment by titanous** [comment]
Looks like there are a bunch of heartbeat failures in the log with `timed out enqueuing operation` from discoverd. @benbjohnson Any idea what causes that error?

**Comment by benbjohnson** [comment]
@titanous It's strange that it's failing to apply a raft command when there's only one node in the cluster. There's a 5 second timeout and the only thing I could think of that would block would be writing the command to the log. I'm not sure why that would take `>5s` though.

**Comment by titanous** [comment]
@benbjohnson Is there any way we can add more detail to this error path?

**Comment by benbjohnson** [comment]
@titanous Once we pass off control to raft there's not a lot of logging we can do. Here's the handoff:

https://github.com/flynn/flynn/blob/master/discoverd/server/store.go#L644-L652

And then raft takes entries off the `applyCh` here:

https://github.com/hashicorp/raft/blob/9dabbbab966c04a0b6efed3cff6960299fed0642/raft.go#L891

It drains the channel completely so there must be something going on during the `leaderLoop`:

https://github.com/hashicorp/raft/blob/9dabbbab966c04a0b6efed3cff6960299fed0642/raft.go#L844-L951

Since we're vendoring it, we could do print statements within there to see where it might be occurring. We could also increase the timeout here:

https://github.com/flynn/flynn/blob/master/discoverd/server/store.go#L645

**Comment by titanous** [comment]
@benbjohnson I don't think increasing the timeout without understanding the problem makes much sense. Would you please make a branch for @temujin9 to try out that has increased logging patched into the raft library so that we can track this down?

**Comment by benbjohnson** [comment]
@titanous I agree that simply bumping the timeout isn't a good solution. I just meant for debugging purposes. If we bumped it to `30s` and the issue stops then it could be long GC pauses or overloaded disk IO. However, if we bump it and it persists then it would seem like there's a larger underlying blocking issue.

@temujin9 I added a `raft-debugging` branch to my fork:

https://github.com/benbjohnson/flynn/tree/raft-debugging

This will dump out a bunch of logging but it should at least tell us where in the leader loop it is stalling.

**Comment by temujin9** [comment]
How much of a dump are we talking? i.e. - do I need to worrying about disks filling up if I leave it on for long periods of time? If so, I'll need to set up a dedicated testbed, and try triggering it intentionally: not impossible, just ups the work required somewhat.

**Comment by benbjohnson** [comment]
@temujin9 It's going to write about 140 characters to the log on every command that goes through raft. I'm not sure exactly how many are going through per second but if there's 10 commands/second executed through Raft then that's 120MB/day (`140 char/cmd × 10 cmds/sec × 86400 sec/day`).

**Comment by temujin9** [comment]
@benbjohnson Okay, that'll be safe to run on our sandbox, at least. I'll get it in tomorrow, unless I'm swamped with other problems.

**Comment by lmars** [comment]
Another example of this:

https://gist.github.com/anonymous/9320be1854676aa267bc
