### ISSUE TITLE
scheduler: Reconnect host event streams intelligently

### ISSUE THREAD

**Issue by jzila** [flynn/flynn#1921]
Currently when a formation, host, and leader event stream gets disconnected, the scheduler attempts to reconnect. We need to do the same with job streams from a host instead of immediately giving up on the host.

As part of this, also remove the automatic host unfollow that happens if we can't connect to a host client when scheduling a job, which will involve needing to pick a different host for the job.

Also figure out how to correctly handle stopping a job when we can't connect to the host running the job to be stopped.

**Comment by lmars** [comment]
Just to expand on the points a little:

> Currently when a formation, host, and leader event stream gets disconnected, the scheduler attempts to reconnect. We need to do the same with job streams from a host instead of immediately giving up on the host.

We need to reconnect the job stream unless unfollowHost was called (see [here](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L570)), which we can determine by checking `stream.Err()`. When reconnecting though, we will create a new stream in the goroutine, so that can race with a call to unfollowHost (which could try and close the stream which is already closed rather than the one we get when we reconnect).

> remove the automatic host unfollow that happens if we can't connect to a host client when scheduling a job, which will involve needing to pick a different host for the job.

This refers to the calls to `unfollowHost` both [here](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L893) and [here](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L905). I'd argue that we should just drop them right now and rely on `unfollowHost` being called [when we receive the down event](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L619-L622), because if `s.Hosts` does not return a host, its service is down and we will get a down event. @jzila WDYT?

> figure out how to correctly handle stopping a job when we can't connect to the host running the job to be stopped

We should continue to try stopping the job until we get a service down event for the given host (which will [mark all the jobs on that host as stopped](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L584-L590), including the one we were trying to stop).
