### ISSUE TITLE
Dev VM is too big

### ISSUE THREAD

**Issue by cweagans** [flynn/flynn#1931]
As a volunteer developer, I'm most likely to be able to have time to work on Flynn when I'm on an airplane, at a conference (i.e. conference center wifi), or after work when I'm traveling (i.e. in a hotel). All of these places typically have one thing in common: the wifi is absolute crap, which makes downloading a 1.1 GB disk image for the VM difficult if not impossible.

Now, one could argue that I should prepare a bit beforehand, and at least download the VM on a good connection, and you'd be right. However, if you look at the current `box.json` URL, you'll see that there were five updates to the box in a two week time span. That two weeks was when I was traveling for work, so by the time I got one box downloaded and started trying to get something done, vagrant started complaining about there being an update to a box on every. single. vagrant. operation.

There are a few ways to help resolve this problem (the one of the box being too big, which implicitly resolves any frustration related to frequent box updates), and I'm willing to pitch in to do it, but when I started trying to dig into it, I didn't see any repository or location in `flynn/flynn` that looked like it was responsible for the creation of the flynn-base box.

Do you have documentation about how this is built? Or a repository that you can open up to the general public?

**Comment by titanous** [comment]
Installing every single update is not required for development, the image is rebuilt as part of the nightly release process and there is very little that changes from release to release. The frequent updates are done because we bake a compiled version of Flynn in for the demo environment. We're probably at a point where it makes sense to split the two environments into different images, which would make the dev VM quite a bit smaller.

The build scripts are here:

https://github.com/flynn/flynn/blob/master/script/release-vm-images
https://github.com/flynn/flynn/tree/master/util/packer

There is also some modernization work in #1720.

Let me know if you have any other questions.

**Comment by cweagans** [comment]
I see. Okay, that makes sense.

I'll take a look at #1720 and then see what I can do about slimming things down a bit. If you want, I can tackle spitting things out into separate VMs too.

**Comment by titanous** [comment]
Sounds good, it'd be great if you could help split them up! Let us know if you have any questions.

**Comment by cweagans** [comment]
I opened a separate issue for splitting the VMs.

I also looked into slimming down this VM, and I'm not sure how feasible it is. After going through what's in place already, there's already a pretty comprehensive set of things to decrease the size of the final VM. The only thing that I saw that *might* decrease the size of the final VM is that the Ubuntu image being used is the "official" one, which is a bit bigger than it really needs to be. https://github.com/chef/bento provides pre-slimmed Ubuntu images (without Chef installed - it's just plain ubuntu), but I'm not sure how much that's going to help, because a lot of the slimming that they do is removing kernel headers and compilers and such, which the Flynn install script is just going add back in.

It might be a more straightforward process to split the VMs instead of going down the path of figuring out what each bit in the OVF image is being used for and whether or not it needs to stay.

**Comment by josephglanville** [comment]
The development image is basically always going to be biggish.

The biggest saving of splitting out the demo environment is going to be saving on the compiled and downloaded flynn components, the largest of which is the postgresql docker container at about 400mb.
We don't need to package this into the development VM because it will be built during the first build of the tree.

We could clear the apt download cache as you suggested too which would also clean up a fair bit of space.

The new build process in #1720 is a simple net install for all platforms bar EC2, using a straightforward pre-seed script. We can customise it to slim down the system further but I think you will find it's already pretty spartan.

**Comment by titanous** [comment]
Looks like #1933 replaces this issue.
