### ISSUE TITLE
host: Error creating AUFS mount

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2044]
Twice now has my Flynn cluster failed to run Redis based on this gist:
https://gist.github.com/lmars/fca0f18b4ecd507fb39a

Only way to recover from it, really, is by re-creating the cluster and trying again.

Gist of the flynn-host error:
https://gist.github.com/rikur/ac413fd781722315517f
Csysdig output during the failure:
https://gist.github.com/rikur/b147ab31327b83da608b

**Comment by lmars** [comment]
The relevant errors from the host log:

```
now=2015-10-29T20:49:40+0000 job.id=ip100094-d81fa905-ae90-4189-b375-e405edab90fc backend=libvirt-lxc fn=run at=checkout
ERRO[158068] Couldn't run auplink before unmount: exit status 22
now=2015-10-29T20:49:40+0000 backend=libvirt-lxc fn=run at=checkout status=error err="error creating aufs mount to /var/lib/docker/aufs/mnt/tmp-ip100094-d81fa905-ae90-4189-b375-e405edab90fc: invalid argument" job.id=ip100094-d81fa905-ae90-4189-b375-e405edab90fc
EROR[10-29|20:49:40] error running job                        app=host pid=3141 host.id=ip100094 fn=AddJob job.id=ip100094-d81fa905-ae90-4189-b375-e405edab90fc err="error creating aufs mount to /var/lib/docker/aufs/mnt/tmp-ip100094-d81fa905-ae90-4189-b375-e405edab90fc: invalid argument"
```

The `auplink` error is coming from the AUFS Docker driver [here](https://github.com/docker/docker/blob/master/daemon/graphdriver/aufs/mount.go#L14-L16), and from analysing the sysdig output, the `EINVAL` is coming from within auplink [here](https://github.com/morfoh/aufs-util/blob/aufs3.2/proc_mnt.c#L94-L97).

I don't currently have any more insight into the root cause of this issue.

**Comment by lmars** [comment]
I was getting this consistently in EC2 so I dug a little deeper.

When starting a job, we call `pinkerton.Checkout` to create an AUFS mount, which subsequently calls [aufsMount](https://github.com/docker/docker/blob/e589dc7424dfad993f1fc646b66fa04306a2df2d/daemon/graphdriver/aufs/aufs.go#L415-L462). The auplink related error is being printed when [this defer](https://github.com/docker/docker/blob/e589dc7424dfad993f1fc646b66fa04306a2df2d/daemon/graphdriver/aufs/aufs.go#L416-L420) runs, but the actual error is `EINVAL` from calling `mount(2)` [here](https://github.com/docker/docker/blob/e589dc7424dfad993f1fc646b66fa04306a2df2d/daemon/graphdriver/aufs/aufs.go#L442).

I verified this by looking more closely in sysdig:

```
3285625 23:51:38.606750996 4 flynn-host (12681) < mount res=-22(EINVAL) dev=none dir=/var/lib/docker/aufs/mnt/tmp-host1-0be9461b-fca0-4cac-bd18-e01230140b95 type=aufs 
...
3286052 23:51:38.608552038 2 auplink (14411) > write fd=2(<f>/dev/null) size=8 
3286053 23:51:38.608553120 2 auplink (14411) < write res=8 data=auplink: 
3286054 23:51:38.608554719 2 auplink (14411) > write fd=2(<f>/dev/null) size=15 
3286055 23:51:38.608555030 2 auplink (14411) < write res=15 data=proc_mnt.c:96:  
3286056 23:51:38.608555872 2 auplink (14411) > write fd=2(<f>/dev/null) size=71 
3286057 23:51:38.608556214 2 auplink (14411) < write res=71 data=/var/lib/docker/aufs/mnt/tmp-host1-0be9461b-fca0-4cac-bd18-e01230140b95 
3286058 23:51:38.608563943 2 auplink (14411) > write fd=2(<f>/dev/null) size=18 
3286059 23:51:38.608564276 2 auplink (14411) < write res=18 data=: Invalid argument 
3286060 23:51:38.608564806 2 auplink (14411) > write fd=2(<f>/dev/null) size=1 
3286061 23:51:38.608565097 2 auplink (14411) < write res=1 data=. 
3286062 23:51:38.608571420 2 auplink (14411) > exit_group 
```

There is also this line in `dmesg`:

```
[83166.857411] aufs au_xino_create:745:flynn-host[12681]: open /dev/shm/aufs.xino(-17)
```

I have no idea what the issue is, but given it only happens a small number of times, we should just retry (I will PR soon).
