### ISSUE TITLE
Documentation request: Basic architechture description

### ISSUE THREAD

**Issue by megamattron** [flynn/flynn#2169]
Apologies if I missed this in the docs, but I'd love a high level overview of how routing happens. Do you run the front end routing that dispatch requests to our servers? Or do you use local infrastructure like ELB? If you do run the routers, on what network do they run and would they introduce different amounts of latency depending on what provider we deploy to?

Thanks very much, love the project.

**Comment by lmars** [comment]
@megamattron we are currently working on improving architecture documentation, but to answer your specific question:

Flynn includes a router which runs on each node in a cluster and listens for HTTP requests on ports 80 / 443 (TLS).

Apps register routes so that hostnames map to services (e.g. `web.example.com` routes to a service named `my-app-web`), and if a process is scaled to N, there will be N addresses associated with the corresponding service, so when a request hits the router with a hostname which maps to a service, the request is round-robined to one of those N processes.

Flynn does not interact with infrastructure providers when it comes to routing, but you can of course put your Flynn nodes behind a load balancer if you wish.

I hope that answers your question, but feel free to ask if you want more information.

**Comment by megamattron** [comment]
Thanks for the answer, I don't think I'm quite clear on how the user's request finds it's initial router. I understand that each node runs a router, but with N nodes, is it the DNS that maps web.example.com to all of the nodes? Or does the DNS point to a single node's router, which then routes to one of the other nodes?

Sorry if I'm missing something obvious. I'm trying to map my usual understanding of load balanced routing where there's an ELB or something similar that's the first point of contact for the user's request. I can't quite see where that happens in this setup.

Thanks again.

**Comment by josephglanville** [comment]
@megamattron yes, the DNS record for the cluster contains multiple A records. When the client resolver looks up this address the DNS server will return these A records in a randomised order and the client will attempt to contact one, trying another if the first fails.

All of these entries host a router that can serve the client request.

It's recommended you use a DNS service that supports active health checks like Route53 so that you can route routes requests only to healthy nodes.

**Comment by megamattron** [comment]
Makes sense, thanks. I'm deploying to digital ocean currently, so does that utilize floating IPs to achieve this, or does whatever DNS handles flynnhub.com do this with multiple A records?

Thanks very much.

**Comment by titanous** [comment]
Digital Ocean has no way of doing DNS health checks, so you'll need to use an external provider if you want that.

**Comment by megamattron** [comment]
So I am correct in understanding that my current deployment to digital ocean then uses flynnhub.com DNS multiple A records with no health checks? Meaning if one of the servers failed it would still receive user requests?

**Comment by titanous** [comment]
Correct.

**Comment by megamattron** [comment]
Got it. Thanks for your help in understanding.

**Comment by titanous** [comment]
Architecture docs have been up for a while: https://flynn.io/docs/architecture
