### ISSUE TITLE
controller: "cached plan must not change result type"

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2235]
```text
ERROR: cached plan must not change result type (SQLSTATE 0A000)
```

Sounds like a race between the DB migrations and preparing statements when creating connections.

https://gist.github.com/anonymous/2eedd040b6bf05bcd1da

**Comment by josephglanville** [comment]
So this happens when you have a prepared query cached on your session and when you go to execute it the underlying schema has changed the type of a column.

The fix is probably to catch this error and release the connection, fetching new conns from the pool until we establish a new connection.

It might be possible to trigger a refresh of the pgx pool eagerly but I think the lazy approach is probably going to yield better results.

The good thing about this error is we know for sure that nothing was executed, making retrying the query very straightforward.

**Comment by josephglanville** [comment]
I have a proposed fix for this here: https://github.com/flynn/flynn/tree/fix-cached-query-plan

The upstream issue and PR: https://github.com/jackc/pgx/issues/110 https://github.com/jackc/pgx/issues/111
