### ISSUE TITLE
Dashboard: process list should be in scrollable or paginated frame, have filters

### ISSUE THREAD

**Issue by nobert** [flynn/flynn#2254]
The dashboard processlist on a long-running application eventually becomes slow to load and requires scrolling. Ideally, this view would have filters, to view e.g. only running/crashed, or most recent _n_ entries. It should also either be in a scrollable frame, or have pagination, so that the log display is always visible.

**Comment by jvatic** [comment]
I assume this issue is referring to the log view and not the formation scaling section of the main app view. #2907 implements a scrollable process list. Once filtering capabilities have been added this issue can be closed.

**Comment by schu34** [comment]
Any word on this? for me the logs page is almost unusable because of the time it takes to load the deploy history (firefox gives me a "this page is slow" warning when I try to scroll"). I think loading only the last n deploys by default with the option to show more would be the simplest solution. I'm pretty busy at work these days but I may be able to look into implementing it this weekend if that solution is cool with you guys.
