### ISSUE TITLE
Can't recover after reboot

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#2523]
After shutting down all 3 nodes and starting them back up I can get the cluster to work. Using `sudo flynn-host fix --min-hosts 3` gives an error of

```
unable to list hosts from discoverd, falling back to peer IP list error="Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
12:33:36.225598 host.go:140: error connecting to discoverd, use --peer-ips: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused
```

I've also tried `sudo rm /var/lib/flynn/host-state.bolt; sudo start flynn-host; flynn-host bootstrap` which gives the error

```
12:46:56.933465 check online-hosts
12:46:56.934738 require-env require-env
12:46:56.934839 require-env require-env error: Missing required environment variable(s): CLUSTER_DOMAIN
```

**Comment by josephglanville** [comment]
Please provide debug info for all of the nodes with `flynn-host collect-debug-info`.
I suspect a few things may have been in play here but can't tell without logs.

Can you also provide information about how you restarted the nodes? Clean reboots? Hard power off? etc.

**Comment by dottodot** [comment]
It was a hard power off

node1  https://gist.github.com/4a2c29a87b5763ab337a 
node2  https://gist.github.com/25c3582d79ac3c071918 
node3  https://gist.github.com/fa62dde362ce230fb489

**Comment by josephglanville** [comment]
Ok, do what happened here was that node2 got stuck due to #2481 which I just fixed in  #2522.
node1 and node3 come up fine and the cluster-monitor started but it didn't progress to fixing the cluster (even though it technically could) because of a safety condition it currently has built in that prevents it acting unless all of the initial bootstrap machines come back.

To recover your cluster for now you need replace node2, either with a brand new machine or be re-installing flynn with --clean and then starting the daemon with --peer-ips or with the discovery token so that it re-joins the cluster.

**Comment by josephglanville** [comment]
Oh, I didn't read the second part where you deleted the flynn-host state database.. You are going to need to replace those nodes entirely that you have run that on as you might have damaged the cluster beyond repair.

Until #2522 is merged and released best to avoid hard power off for now.

**Comment by dottodot** [comment]
Had to clean install them all, not really an issue as just starting out, and shouldn't need to shutdown again anytime soon.
