### ISSUE TITLE
flynn-host scheduler stream timeout?

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2546]
While looking over some logs, I noticed that the scheduler appears to be reconnecting to the job stream from `flynn-host` every 5s. This is probably due to a request timeout.

**Comment by lmars** [comment]
Ah yes, not sure how I haven't spotted this before! There is a [5s timeout](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L140) on the cluster HTTP client, which doesn't make sense for streaming requests, especially ones which auto-reconnect.

I wonder whether [ResumingStream](https://github.com/flynn/flynn/blob/master/pkg/httpclient/json.go#L199-L209) should dup the underlying `http.Client` and zero out the timeout, since it never makes sense to have a timeout with a resuming stream. WDYT?

**Comment by titanous** [comment]
Yeah, I think zeroing out the timeout is reasonable.
