### ISSUE TITLE
Add support for blobs in S3

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2622]
If S3 is available, we should use it instead of Postgres to store blobs.

**Comment by temujin9** [comment]
Oversized postgres backups have been dying regularly on at least one cluster (and probably also triggering other issues, as well). Removing this from postgres should help substantially with that.

**Comment by IsNull** [comment]
Some thoughts on this one:

Flynn is very attractive since it positions itself as a self-hostable alternative in the PaaS world, but depending on S3 for blob storage destroys this advantage. I understand this is an optional feature, but since it is handled as a solution to a problem (blob store, backup performance), its not really that optional.

A backup of the cluster should restore it to a state it can run the same way. So you may have to backup the currently executed slugs - but there is no need to backup unused slugs. Same is true for git repos. They can be freshly checked out if required. Slugs can be rebuilt if necessary. Related #2900, there should be a cache of built slugs, but it should not grow indefinitely. Maybe just cache the last 5-10 slugs.
This would probably even suffice - just ensure that during the lifetime of an application, its cached data does not grow all the time. 

Improving this and only keeping data which is really necessary in the backup should solve the issue without requiring a separate blob-store.

**Comment by lmars** [comment]
@IsNull 

> A backup of the cluster should restore it to a state it can run the same way. So you may have to backup the currently executed slugs - but there is no need to backup unused slugs

It seems like you are describing backing up a specific app with just its current slug, which is exactly what `flynn -a $app export` does. A full cluster backup on the other hand backs up everything, if you want to omit old slugs from a cluster backup then you should delete them first.

> Related #2900, there should be a cache of built slugs, but it should not grow indefinitely. Maybe just cache the last 5-10 slugs.
This would probably even suffice - just ensure that during the lifetime of an application, its cached data does not grow all the time.

Flynn has a mechanism to manually delete old slugs (`flynn release delete <id>`) and also has a GC option so that only the last N slugs are kept (#2769).

#2900 is a related bug which we will fix soon.

**Comment by philiplb** [comment]
Hi,
is there a migration path from the PostgreSQL Blobstore to the new S3 Blobstore?

**Comment by philiplb** [comment]
Found it. :)
```bash
flynn -a blobstore run -e /bin/flynn-blobstore-migrate -- -delete
```
