### ISSUE TITLE
Flynn node loses network connectivity intermittently

### ISSUE THREAD

**Issue by ohhatiya** [flynn/flynn#2743]
We have two clusters that each have a single node experiencing repeated, intermittent network connectivity issues. The failing nodes have log messages from nf_conntrack like:

```
nf_conntrack: falling back to vmalloc.
```

The normal nodes do not have such log messages. That makes it seem relevant, but I don't know for sure.

Here's the debug info from a node that's experiencing the issue.
https://bazaarvoice.box.com/s/tsig7lt3rle2ytorz7d3bsymantitb69

Here are the last few times the issue occurred (but not a comprehensive listing) on that node:
2016-04-26 01:08Z
2016-04-26 02:07Z
2016-04-26 02:22Z
2016-04-26 02:25Z

**Comment by titanous** [comment]
What errors are triggered by the network issues?

**Comment by ohhatiya** [comment]
Network connectivity of the entire node goes out for some time. So any requests to applications running on the node fail, for one.

**Comment by titanous** [comment]
If you have any instances that have experienced this problem, I'd like to see the full console log for that time period from AWS (containing kernel log messages).

**Comment by ohhatiya** [comment]
Here's the kernel log from an instance that experienced network issues today. Note that it's a different instance than the one the debug info in the original message is from (which has since been recycled).

https://gist.github.com/anonymous/daf5ed0ba0fdbc1cb677d1fed13c5110

**Comment by titanous** [comment]
There is nothing obviously wrong that's network-related in the kernel log. There are a few ZFS stalls, but that should not impact the network. Do you have CPU/network metrics available to correlate with the downtime you observed?

**Comment by tianx2** [comment]
This appears to still be happening. Seems to be related to #2775. Going to just talk about the issue here instead of re-opening the other one. Our users today reported getting 500 errors during the git push process.

```
2016-05-09T15:08:35.871951Z app[app.ip1010055214-66e4f5a2-47d9-4dd8-9193-764e6919ec72]: t=2016-05-09T15:08:35+0000 lvl=eror msg=getApp component=gitreceive req_id=c8c37628-e928-497e-9480-d327d697d7cb error="Get http://controller.discoverd/apps/terminus: dial tcp: lookup controller.discoverd: no DNS servers"
2016-05-09T15:08:35.872078Z app[app.ip1010055214-66e4f5a2-47d9-4dd8-9193-764e6919ec72]: t=2016-05-09T15:08:35+0000 lvl=info msg="request completed" component=gitreceive req_id=c8c37628-e928-497e-9480-d327d697d7cb status=500 duration=29.514687152s
```

In our alerts we seem to have some flakiness with mariadb. Is that tied to discover.d in some way?

Screenshot of metrics during flaky time:

- https://bazaarvoice.box.com/s/ij9guzskyu6qx4rrvvwr6jyapx3y61s6

Logs:
- https://bazaarvoice.box.com/s/aqi0xe6fp3rimacu3j7218j67n2vacmw
- https://bazaarvoice.box.com/s/u7xg9t5pzyim6ewgdnnyjt0gx4y9w0j0
- https://bazaarvoice.box.com/s/83paihnokndkubipreln4yqntu4k5bn5
- https://bazaarvoice.box.com/s/p4qp71w30nvsdiix1e600h0gnkxnfd0v
- https://bazaarvoice.box.com/s/8pjlf10ait221ajokry0b537uz7vceie

**Comment by titanous** [comment]
It looks like there are consistent spikes that start ~15 minutes into each hour. I wonder if the `pg_dump` process as part of scheduled backups is the culprit.

**Comment by temujin9** [comment]
@titanous That is entirely plausible. Can we rate limit that somehow?

**Comment by titanous** [comment]
pg_dump was moved to the background partition in #3482. I haven't heard anything about this issue recently, so closing.
