### ISSUE TITLE
Strange deployment behaviour - high cpu spike

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#2755]
At the moment I'm getting about a 10% success rate when deploying and I keep getting the following error

```
remote: Error deploying app release: timed out waiting for deployment completion
To https://git.cloud.server.co.uk/test.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.cloud.server.co.uk/test.git'
```

On the last attempt it actually did update despite that message. I was watching the logs and I could see my app launch successfully but it than hung on Creating release... before showing this message.

I'm also seeing quite a lot of CPU spikes especially when trying to deploy. normally the cpu usage is around 8% but on deploy it hit 100%,

Here my debug info from one server https://gist.github.com/anonymous/9a4942cbb3c1934b84372fd8b71058df

**Comment by titanous** [comment]
What is the name of the app are you having trouble deploying?

**Comment by dottodot** [comment]
bailey-staging

**Comment by titanous** [comment]
As mentioned before, this is due to the default timeout being lower than the time it takes your app to start, try the workaround mentioned here: https://github.com/flynn/flynn/issues/2726#issuecomment-213057487

High CPU usage during deploys is normal. I'll bump up exposing exposing the timeout in the CLI.
