### ISSUE TITLE
New router attempting to connect to dead node

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2784]
We are fairly regularly losing nodes to AWS health-checks. Their replacements are not coming up correctly: the router does not appear to be working, complaining of:
```
t=2016-05-05T16:14:40+0000 lvl=eror msg="error starting HTTP listener" app=router fn=Start err="Get http://10.100.52.47:1111/services/flynn-usage-example-web: dial tcp 10.100.52.47:1111: no route to host"
```

That IP address is the one which got killed. It does not show up in `flynn-host list`. Using `flynn-host demote -f 10.100.52.47`, and then stopping the existing router instance (which was sitting around, "healthy", despite its failure), fixed the problem.

https://gist.github.com/51b60122e78b69dd1dc4e991ad7a9eb6 is the debug-info for the new node (the others all 405ed on gist upload, and I suspect were less important anyway).

(Paging @josephglanville per @titanous: your input on what's going on here with discoverd is requested.)

**Comment by josephglanville** [comment]
Ok I see what is happening here. Basically discoverd has a fairly primitive proxy feature what when it's not a Raft member it will try redirect to what it considers and up to date list of Raft members which is stored in it's `DISCOVERD_PEERS` environment variable.
Right now every job on a node attempts to use the local discoverd, which will redirect requests randomly using the aforementioned proxying.
Unfortunately in the case of a loss of node, that is then replaced automatically `DISCOVERD_PEERS` won't be updated. I already knew this was to become a problem so I have 2 parts of the solution in-flight right now.

The first is the merge of the smarter discoverd client: #2173
With this code in use the router wouldn't even try utilize the local discoverd as a proxy as it will know it's not in the Raft peer set. Unfortunately it will still get out of sync over-time if the Raft peers are continually replaced because even if you do a discoverd deployment to update `DISCOVERD_PEERS` the router and other processes won't get the new list of peers.

Which brings me to the second part of the solution. Which is to have all proxy discoverd instances and the smart client stream changes to the peer set so that the client will be able to keep up with node replacements etc. `flynn-host` will also need to do this so that it can bootstrap new jobs with the most up to date list of peers (right now this happens through doing a discoverd deployment to update the DISCOVERD_PEERS var)

The combined result will be that the client will be able to retry requests until it finds a peer, allowing it to operate in the face of multiple discoverd nodes being down and once a demote/promote comes in it will update it's internal list of peers.

**Comment by titanous** [comment]
Separately from that, I think the error logged should probably cause the router to exit instead of hanging in a broken state.

**Comment by josephglanville** [comment]
Agreed, it should definitely not do that.

**Comment by titanous** [comment]
Router shutdown hang is fixed in #2791.

**Comment by temujin9** [comment]
@titanous Unfortunately, updating DISCOVERD_PEERS does not work on a test system: the `flynn env` command returns "timed out waiting for discoverd deployment (expected=5 actual=0)", and subsequent `flynn ps` show the new release's jobs stuck at pending and rolling over.

**Comment by josephglanville** [comment]
@temujin9 if the jobs were stuck in pending that sounds like a scheduler bug.
Can you post the debug info so we can take a look?

/cc @lmars

**Comment by temujin9** [comment]
https://gist.github.com/7ae006458931e998873f73cf779bcc5f is the new node.

**Comment by josephglanville** [comment]
@temujin9 did you happen to set `DISCOVERD_PEERS` to `10.100.39.215`?

It needs to be set to the new set of peers, i.e something like: `10.100.39.214:1111,10.100.39.215:1111,10.100.42.183:1111,10.100.44.160:1111,10.100.44.162:1111`

**Comment by lmars** [comment]
To clarify, the pending jobs were restarts of crashed `discoverd` jobs, with a typical crash having errors like:

```
set port slice: missing port in address 10.100.39.215
10.100.39.214
10.100.43.245
10.100.44.160
10.100.44.162
```

So it seems to be a badly configured environment variable as @josephglanville mentioned.

**Comment by temujin9** [comment]
Damn. I swear I'd done that one right, but the evidence seems against me. Retrying it now.

**Comment by temujin9** [comment]
This is now fixed.
