### ISSUE TITLE
my PHP (Laravel) app was detected as Node.js

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#2861]
my root directory

```
Procfile
artisan		
composer.json	
config		
gulpfile.js	
phpspec.yml	
public		
resources
storage
app
bootstrap	
composer.lock	
database	
package.json	
phpunit.xml	
readme.md	
server.php	
tests
```

how can I undo all that and force Flynn to detect it as PHP?

**Comment by josephglanville** [comment]
It's being detected as Node.JS because of `package.json` being present in the root.
You can either set the build pack explicitly with this command:
`flynn env set BUILDPACK_URL "https://github.com/heroku/heroku-buildpack-php"`

Or you could exclude package.json from the slug compilation stage by creating a `.slugignore` file in the root of your application that contains:
`package.json`

**Comment by roquie** [comment]
@josephglanville Okay, but how to install & build npm dependies with composer dependies? My app have an frontend and backend in the same directory and php-buildpack can't works properly. One way to exit, it to fork php-buildpack repository and add these option himself?

**Comment by roquie** [comment]
If I'll to create `.buildpacks`file and add two [two](https://flynn.io/docs/apps#buildpacks) buildpacks: node and php. It should be install Node dependencies and composer dependencies? Right?
