### ISSUE TITLE
let flynn-host generate a proper `flynn cluster add` line

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#2873]
It would be useful if flynn-host had a command for printing a proper `flynn cluster add` line to the console, ready for copy and pastel

**Comment by imjorge** [comment]
This is somehow a recurring topic on #flynn IRC channel. The recommended actions are:

- get the controller key by running this command on the host

```
flynn-host ps | grep controller | grep web | tail -1 | awk '{print $1}' | xargs flynn-host inspect | grep -F 'ENV[AUTH_KEY]'
```

- and if you set CLUSTER_DOMAIN to your cluster's domain, you can grab the TLS pin with:

```
openssl s_client -connect controller.$CLUSTER_DOMAIN:443 -servername controller.$CLUSTER_DOMAIN 2>/dev/null </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | openssl x509 -inform PEM -outform DER | openssl dgst -binary -sha256 | openssl base64
```

- and change accordingly on `flynn cluster add` command:

```
flynn cluster add -p <tls pin> <cluster name> <controller domain> <controller key>
```

**Comment by imjorge** [comment]
I am thinking on implementing this one as a `flynn-host cli`. To get the controller key we could go the obvious route and apply the sequence above, reusing code from `flynn-host ps` and `flynn-host inspect`. Is there a better way?

/cc @lmars @titanous

**Comment by imjorge** [comment]
I guess another option would be to dump such a file like `/etc/flynn/cli.json` during bootstrap. This has the advantage that it does not require the controller job web process (previous strategy) to be running in order to get the data. And it is faster, obviously. But would have to be kept in sync with cluster migrations, changes of certificate, ... Also, if we bootstraped in a old `flynn-host` version, the file would not exist. It would have to be generated somewhere during first migration?

**Comment by lmars** [comment]
@imjorge I think for now we should add a command like `flynn-host cluster-add-command` which gets the key from the most recent controller web job and generates the pin from the most recent router job (we already do something similar [here](https://github.com/flynn/flynn/blob/master/test/cluster2/cluster.go#L283-L301)).

**Comment by imjorge** [comment]
@lmars great. I will go ahead and implement it like that.
