### ISSUE TITLE
git submodules don't work

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#2906]
if your repo has a git submodule, it will not work. 

```
remote: Host key verification failed.
fatal: Could not read from remote repository.
remote: Please make sure you have the correct access rights
remote: and the repository exists.
remote: Clone of 'git@gitlab.*****/static-assets.git' into submodule path 'static-data' failed
remote: tar: This does not look like a tar archive
remote: tar: Exiting with failure status due to previous errors
remote: Build failed: exec: job exited with status 2
```

heroku [supports](https://devcenter.heroku.com/articles/git-submodules) this by the way.

**Comment by lmars** [comment]
@hadifarnoud since you are pulling a private repo, gitreceive needs an SSH host key + private key which has appropriate access.

You can set them with:

```
$ flynn -a gitreceive env set SSH_CLIENT_HOSTS="$(cat ~/.ssh/known_hosts)" SSH_CLIENT_KEY="$(cat ~/.ssh/mykey)"
```

where `~/.ssh/mykey` is a private SSH key which has access to the repo, and `~/.ssh/known_hosts` contains a host key for the host you are pulling from.

**Comment by hadifarnoud** [comment]
thanks @lmars. would be great to add this on docs too

**Comment by andymilga** [comment]
@lmars i got SSH_CLIENT_KEY variable for application. I see private_key via cli
(like  'flynn -a #app_name env' ) and i see it in dashboard, but when i'm redeploying app - no .ssh directory created in /app.
