### ISSUE TITLE
mongodb: Unable to force set replica set version number

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3102]
`MongoDBSuite.TestDeploySingleAsync` is failing frequently in CI:

https://ci.flynn.io/builds/20160712014542-f0c0e82d
https://ci.flynn.io/builds/20160712011650-c222b27e
https://ci.flynn.io/builds/20160711193301-f74c5698

**Comment by josephglanville** [comment]
This effects the multiple async test too and seems to be a race or other transient bug during primary failover that results in downstream sync not being reported correctly.
I am going to run some tests over this weekend and try get to the bottom of it, may have to add some instrumentation that can run in CI as it's not reproducible on my development environment.

**Comment by josephglanville** [comment]
The bug is worse than originally thought. What is happening here is the new primary is coming up, running `assumePrimary` and updating the replica set with itself as the first peer and election priority. However, the still running primary is then overwriting this when it gets the state update.
So there is either a bug in the changes to Sirenia to support the flat replication topology or a bug in the way the MongoDB process wrapper implements `assumePrimary` that results in what should be a deposed Primary carrying on it's merry way until it's shutdown.

**Comment by josephglanville** [comment]
This has been solved in the medium term by ensuring the heartbeater isn't closed until after the peer state machine has shut down.

However there still exists a potential safety issue. This is fixable by having control over the replica set version number. Unfortunately this isn't possible right now in MongoDB due to a behaviour of the server when using the force replSetReconfig command. An upstream bug has been filed at https://jira.mongodb.org/browse/SERVER-25205. With any luck the MongoDB team will come up with a solution that allows us control over this field.

**Comment by lmars** [comment]
The test is no longer failing but we I'll leave this issue open to track the inability to forcibly set the replica set version number when necessary.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
