### ISSUE TITLE
Host Groups

### ISSUE THREAD

**Issue by mgwilliams** [flynn/flynn#3126]
It would be nice if flynn could scale across host groups rather than individual hosts. This would allow the hosts in one rack/AZ/DC/etc to be grouped together, so that when an app is scaled, the round robin scheduler would ensure an instance in each group (AZ).

**Comment by lmars** [comment]
This doesn't seem like too much work, we just need to modify the slice returned from [`scheduler.ShuffledHosts`](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L697) so that it is shuffled in a grouped fashion (rather than just [at random](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L829-L839)), with the group coming from some host tag.

**Comment by bbaptist** [comment]
Would this also give us the ability to say that say the database portion of Flynn runs on a specific group?

**Comment by lmars** [comment]
@bbaptist that is already possible using tags (e.g. tag a group of hosts with `db=true` then for example update the postgres release with `flynn -a postgres scale postgres=3,db=true web=2`). We could probably improve the workflow though.

**Comment by thomasfedb** [comment]
This is an important feature for me. Currently I can ensure the cluster survives in the scenarios I require, but I can't ensure the DB survives.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
