### ISSUE TITLE
Docker containers: /dev/urandom: Permission denied

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3306]
I can't use urandom to generate random passwords on container startup:

**What I'm trying to do:**
```
RANDOM_PASS="$(/dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-10})"
```
**What I get instead:**
```
init.sh line 112: /dev/urandom: Permission denied
```

This works great outside of flynn.

**Comment by lmars** [comment]
@onnimonni your command is trying to execute `/dev/urandom` which is failing because `/dev/urandom` is not executable.

You probably want to use `cat` to read from it instead:

```
$ RANDOM_PASS="$(cat /dev/urandom | tr -dc _A-Z-a-z-0-9 | head -c${1:-10})"

$ echo $RANDOM_PASS
Ixqjz79fo7
```

You could also use [`openssl rand`](https://www-origin.openssl.org/docs/manmaster/apps/rand.html) to generate random strings.
