### ISSUE TITLE
Reboot cluster, flynn-host fix is not working...

### ISSUE THREAD

**Issue by jwaldrip** [flynn/flynn#3320]
I rebooted each node in the cluster, I am not able to see any of the hosts or recover the cluster.

Running this on each host does nothing.

```sh
$ sudo start flynn-host
start: Job is already running: flynn-host
$ sudo flynn-host fix --min-hosts=3 --peer-ips=10.0.0.2,10.0.1.2,10.0.2.2
EROR[08-22|05:53:19] unable to list hosts from discoverd, falling back to peer IP list error="object_not_found: service not found"
```

**Comment by josephglanville** [comment]
Looks like something is up with the `discoverd` cluster. Can you post gist or tarball output from `flynn-host collect-debug-info` from each host in the cluster.

**Comment by jwaldrip** [comment]
https://dl.dropboxusercontent.com/u/16948872/flynn-host-debug018001234/flynn-host-debug.tar.gz
https://dl.dropboxusercontent.com/u/16948872/flynn-host-debug130026616/flynn-host-debug.tar.gz
https://dl.dropboxusercontent.com/u/16948872/flynn-host-debug250803535/flynn-host-debug.tar.gz

**Comment by josephglanville** [comment]
The `discoverd` cluster seems to have failed to resurrect because RPCs were timing out between the peers so it wasn't able to elect a leader after the reboot.

This can be seen in the logs as each of the `discoverd` processes try to participate in the election but don't succeed in reaching any of the other peers:
```
305 <0>1 2016-08-22T05:59:44.046324354Z stagingflynnhostinstance2 2d32bf88-e81a-48d1-b044-62a21d25ea1a app.stagingflynnhostinstance2-6fbc5dc0-cc3f-4a6c-b12b-aeac5d10f2aa ID2 [flynn seq="2421"] 2016/08/22 05:59:44 [ERR] raft: Failed to make RequestVote RPC to 10.0.1.2:1111: dial tcp 10.0.1.2:1111: i/o timeout
```
Eventually timing out (which is perhaps a behaviour we should reconsider) and leaving the cluster in a somewhat bricked state:
```
217 <0>1 2016-08-22T05:59:44.938909259Z stagingflynnhostinstance2 2d32bf88-e81a-48d1-b044-62a21d25ea1a app.stagingflynnhostinstance2-6fbc5dc0-cc3f-4a6c-b12b-aeac5d10f2aa ID2 [flynn seq="2422"] timed out waiting for leader
```

The IP addresses from the debug logs look correct though.
Perhaps there is something happening at the network level that was preventing communication?

@titanous perhaps we should change `discoverd` to wait forever rather than exiting after not being able to attain a leader?

**Comment by jwaldrip** [comment]
So what am I to do to recover the cluster?

**Comment by josephglanville** [comment]
Best course of action is actually probably to restart `flynn-host` on each node, it should restart `discoverd` which assuming whatever caused the connection issues between the hosts is resolved.

**Comment by jwaldrip** [comment]
This was a networking issue. Cluster auto-recovered after rebooting the instances.

**Comment by titanous** [comment]
@josephglanville Yeah, makes sense, I've opened #3321
