### ISSUE TITLE
"flynn -a gitreceive env set" returns "timed out waiting for job events: map[app:map[up:2]]"

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3324]
This happens repeatedly (looped in the init script) on a newly restored cluster. 

https://gist.github.com/f3b193a2096258fcc13ccd5d61386ff5

(Only one of the nodes was able to return collect-debug-info correctly, the other two hit 405s despite very similar log sizes of ~90MB).

**Comment by lmars** [comment]
This is a bug in the scheduler where it is blocked trying to persist the state of job `56ae78e8-d074-4722-bfa6-e53ee2f17e5b` with an invalid state, triggering the following error in the controller:

```
t=2016-08-23T18:23:44+0000 lvl=info msg="request started" component=controller req_id=a66bfa34-0ca3-4fb7-bfc6-934ac8f10784 method=PUT path=/apps/35cf498d-b14b-44c5-a4f0-03475e2d7f11/jobs/56ae78e8-d074-4722-bfa6-e53ee2f17e5b client_ip=10
t=2016-08-23T18:23:44+0000 lvl=eror msg="ERROR: insert or update on table \"job_cache\" violates foreign key constraint \"job_state_fkey\" (SQLSTATE 23503)" component=controller req_id=a66bfa34-0ca3-4fb7-bfc6-934ac8f10784
t=2016-08-23T18:23:44+0000 lvl=info msg="request completed" component=controller req_id=a66bfa34-0ca3-4fb7-bfc6-934ac8f10784 status=500 duration=3.461748ms
```

Because the error is a `pgx.PgError`, it is marked as [retryable](https://github.com/flynn/flynn/blob/master/pkg/httphelper/httphelper.go#L177-L178), so the scheduler retries for [one minute](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L843), which blocks all other job persistence because there is only a single goroutine so that job events are persisted in order.

Since the scheduler tries to sync job states every 30s, it continually queued up the persistence of this job, thus blocking the put jobs goroutine continuously.

We need to investigate / fix the following:

* Why was the scheduler persisting a job with an invalid state, and what was that invalid state?
* A postgres foreign key violation should not be a retryable error (perhaps always convert to `ct.ValidationError`?)
* Job events only need to be ordered per job (i.e. always create `starting` events before `up` events), so the scheduler should have a goroutine _per job_ doing persistence with retries (rather than a single goroutine for all job persistence which can block for up to a minute)
* If a job state is being persisted (but possibly failing), don't queue up another persistence of the same job state

**Comment by titanous** [comment]
Is this related to #3274?

**Comment by lmars** [comment]
@titanous certainly looks related yes.
