### ISSUE TITLE
thoughts about incorporating kubernetes?

### ISSUE THREAD

**Issue by jokeyrhyme** [flynn/flynn#3330]
I've been watching the open-source PaaS / CaaS space for a while now, and I've noticed that OpenShift and Deis (and probably others) have restructured themselves around Kubernetes:

- https://github.com/openshift/origin

- https://github.com/deis/workflow

- https://github.com/kubernetes/kubernetes

Kubernetes is not yet self-hosting, so its control plane is not yet running as highly-available / self-managed containers. I believe Flynn _is_ self-hosting currently, so it probably makes sense to wait for this upstream work to be completed over the next few Kubernetes releases:

- https://github.com/kubernetes/community/blob/master/sig-cluster-lifecycle/README.md

What other benefits and concerns would there be here?

**Comment by titanous** [comment]
Flynn predates Kubernetes so it wasn’t a choice when we were starting out. As you point out, Kubernetes isn’t yet self hosting which disqualifies it for us currently. We continue to monitor advancements in a number of technologies, including Kubernetes, to see if they would make a good addition to Flynn.

The two primary concerns we have about incorporating other technologies into Flynn are the effort required to initially incorporate them as well as their future direction. Most of Flynn’s components were either created exclusively for Flynn, have been forked, or are vendored.

As a result we have a huge amount of control over how they work and relate to other Flynn components. This end-to-end model lets us deliver features faster and more reliably than if we relied on a number of other vendors to maintain components. Because Flynn would be only one among many users of a component like Kubernetes, our voice would carry far less weight in conversations about architectural and API design and feature prioritization and roadmap. That can mean we have to wait for or work around features, which can outweigh the benefits of adopting existing technology.

**Comment by jokeyrhyme** [comment]
Thanks. That all makes sense.

**Comment by smolinari** [comment]
The open questions in my mind are, 

1. Does Flynn already offer the features available in Kubernetes?
2. If only partially, which features does Flynn offer?
2. Which ones are missing?

Deis and Flynn seem to be the most "approachable" OSS PaaS solutions. However, being Deis is based on Kubernetes makes it awfully attractive for a Docker based microservices system. Flynn's attractiveness lies in its simplicity, yet still being quite powerful. It's a tough call to make not knowing the deeper details (which I am working on). 

Scott
