### ISSUE TITLE
maximum concurrent addjob calls running

### ISSUE THREAD

**Issue by faddat** [flynn/flynn#3342]
installing onto 4 fresh metal instances running 14.04 hosted at hetzner.  

https://gist.github.com/b8430cb03090f6bea9f3cd6b8d39aabf

Thank you.  If you need anything more, please let me know.

**Comment by josephglanville** [comment]
The `flynn-host` daemon limits the number of jobs that are starting concurrently to avoid saturating system resources. The maximum concurrent AddJob calls message is printed when this limit is hit.
It is a expected that it will be hit during certain scenarios (bootstrapping, restoring from backup and recovery from reboot). This shouldn't be indicative of a problem unless you are seeing this during normal operation (which would normally be caused by a flapping process or similar)

These logs were collected during cluster bootstrap, did the cluster bootstrap successfully?

**Comment by faddat** [comment]
The cluster does not bootstrap successfully.  It stops after I get this
error message, unfortunatley.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by titanous** [comment]
Do you have the full output from the bootstrap available?

**Comment by faddat** [comment]
Maybe.  I can also relaunch the cluster.  When launching a cluster, what should i be on the lookout for?

**Comment by titanous** [comment]
Relaunching is fine, just get the full output from the installer and the debug info if anything fails.
