### ISSUE TITLE
flannel unhealthy

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3448]
Just noticed in my dashboard it's showing flannel as unhealthy. 

Should I try stopping the flannel jobs to see if it fixes it. Just want to check as don't want to break anything

**Comment by lmars** [comment]
Please run `sudo flynn-host collect-debug-info` and post the resulting gist so we can try and understand why flannel is unhealthy.

**Comment by dottodot** [comment]
https://gist.github.com/22b944c2ced786b6cebe871b1066f6ed 
https://gist.github.com/b44e8ef5488fbcde9b08549ce8dc372c
https://gist.github.com/f9729db9f76cd12d16b52d79b77bee9e

**Comment by dottodot** [comment]
Did you manage to look into this?

**Comment by lmars** [comment]
@dottodot sorry for the delay on this, I have looked through the logs but can't really get a sense of why flannel is reporting as unhealthy.

Looking at the code, nothing is actually logged to understand what the issue is. Would you be able to come into IRC where we can debug this together?

In any case, Flannel being unhealthy is probably not having any effect on your cluster, unless you have noticed anything else not functioning correctly?

**Comment by dottodot** [comment]
this was fixed by adding the following firewall rule

```
sudo ufw allow in on flannel.1
```
