### ISSUE TITLE
Run command line for a docker image?

### ISSUE THREAD

**Issue by aghasoroush** [flynn/flynn#3454]
Hi again,
Is there any way to run a custom docker command like this ? 
I wanna install gitlab ce from a docker image. I know this is not the complete command, but is there any thing like this ?

docker run --name gitlab-postgresql -d \
    --env 'DB_NAME=gitlabhq_production' \
    --env 'DB_USER=gitlab' --env 'DB_PASS=password' \
    --env 'DB_EXTENSION=pg_trgm' \
    --volume /srv/docker/gitlab/postgresql:/var/lib/postgresql \
    sameersbn/postgresql:9.5-1

**Comment by lmars** [comment]
@aghasoroush you can deploy Docker images to Flynn by following the steps outlined in the following documentation:

https://flynn.io/docs/docker

Flynn does however have a built-in PostgreSQL appliance so it probably makes sense to configure GitLab to use that:

https://flynn.io/docs/databases/postgres

**Comment by aghasoroush** [comment]
Cannot understand how can it be related to my question!
I know about pushing images to flynn, but my question is about passing parameters to docker command

**Comment by lmars** [comment]
@aghasoroush once you have pushed the Docker image, you can set environment variables with `flynn env set`, e.g.:

```shell
$ flynn -a APPNAME env set DB_NAME="gitlabhq_production" DB_USER="gitlab" DB_PASS="password" DB_EXTENSION="pg_trgm"
```

You cannot however achieve the equivalent of the `--volume` flag because Flynn does not support exposing arbitrary host directories to jobs.

PostgreSQL persistence is instead achieved by using the following state machine design:

https://flynn.io/docs/databases#state-machine-design

which is used by the built-in PostgreSQL appliance.

**Comment by aghasoroush** [comment]
@lmars Thanks about great description. I will try it
