### ISSUE TITLE
Unable to restore cluster from backup on digitalocean, stuck on "restore: start"

### ISSUE THREAD

**Issue by ron137** [flynn/flynn#3527]
I tried 4 times to restore my cluster from backup on digitalocean (3 nodes) using the "flynn install" and it's get stuck on: "restore: start".

Local flynn version: v20161018.0
Node flynn-host version: v20161017.1 

here is my debug info of 1 of the nodes:
https://gist.github.com/d51f9025b98f0dd81b7fe16422fec5fe 

this is the installation log:

<script src="https://gist.github.com/ron137/ace4939bc2913a7f695e2a6ea61a47b4.js"></script>

**Comment by josephglanville** [comment]
Hi @ron137 would you be able to put the install log in a gist. I think the Github comment stuff is messing with the formatting.

**Comment by josephglanville** [comment]
So what caused the cluster restore to fail is the MariaDB sync node failed to restore the xtrabackup file from the primary.

Is there any chance your backup doesn't contain any sensitive that you might be able to share with the Flynn team? If so would you be happy to email it to me at joseph@flynn.io?

If not if you could describe what you have done with the MariaDB cluster since installing Flynn that would be great, if I can reproduce this I can likely fix it.

**Comment by ron137** [comment]
I sent you mail with my backup file

**Comment by josephglanville** [comment]
Just an update, I have reproduced the issue.

I haven't been able to identify the root cause but reproducing is a great start, I will let you know how I progress.

Do you need help getting specific data out of the backup or getting a new cluster going before this bug is found and fixed?

**Comment by ron137** [comment]
First of all thank you a lot for the very fast reply!

And I don’t need help getting the data out because I have another cluster that running right now and it works fine.
I just wanted to update the flynn-host to the new release of today but I can’t because of this issue.

I am waiting to your response and again thank you!
Ron

**Comment by josephglanville** [comment]
No problem, we endeavour to reply quickly. :)

I have found the root cause, it's a race condition between the restore process and the initial cluster replication setup. The initial replication setup requires a global read lock due to issuing `FLUSH TABLES WITH READ LOCK` and if the restore starts before this has completed then it obtains a write lock (which conflicts with global read ofcourse) but can't progress because of the replication not currently being active (the write will block on "Waiting for semi-sync ACK from slave").

I will get this fixed ASAP, thanks for reporting and providing the backup.
