### ISSUE TITLE
Allow `flynn ps kill` to receive a list of jobs IDs

### ISSUE THREAD

**Issue by simon0191** [flynn/flynn#3532]
Right now `flynn ps kill` only receives one job ID. Since the command takes some seconds to finish, It would be great to allow `flynn ps kill` to receive a list of jobs IDs like `docker ps kill id1 id2 id3 ...`, that way the user won't have to wait a lot of time if he/she needs to kill multiple  jobs.

If it's ok I can work on the implementation.

**Comment by josephglanville** [comment]
Feel free to take a stab at it. :)

**Comment by lmars** [comment]
@simon0191 `flynn-host stop` accepts multiple IDs (see [here](https://github.com/flynn/flynn/blob/master/host/cli/stop.go)) so that would be a good reference if you implement this change.

Check out our development docs which can help when making code changes:

https://flynn.io/docs/development

You may want to also add a `--quiet` option to `flynn ps` which just prints IDs, then you could kill all jobs with something like:

```
flynn ps --quiet | xargs flynn kill
```

and maybe add a `--type` flag so you could kill all jobs of a single type:

```
flynn ps --type "worker" --quiet | xargs flynn kill
```

(note that above change would eliminate the need for `flynn kill` to take multiple arguments as you could just use `xargs -L1`, but it is still probably useful).

**Comment by simon0191** [comment]
👌 Working on it
