### ISSUE TITLE
Allow t2.small EC2 instance to be picked in Flynn installer 

### ISSUE THREAD

**Issue by alejoescobar** [flynn/flynn#3571]
We recently deployed a Flynn cluster on three t2.small EC2 instances using the Flynn installer. We’ve tested for a couple of months now and it’s been working pretty nice. I would like to give it a shot at allowing users to choose this type of instances, of course giving them a warning that they’re not recommended. I believe this is a good addition as it allowed us to test flynn for a lot less than we expected (50USD/month instead of 100USD/month).

Let me know what you think.

**Comment by titanous** [comment]
Our experience has been that the CPU throttling system in the t2 series of instances leads to all sorts of strange failures, and also has an impact on network performance that can break database replication and service discovery consensus.

Due to the support burden of diagnosing these issues, we will not be adding the t2 instance class to the installer. You are of course free to either modify the installer or use the SSH option, but we don't recommend it and will not provide support for Flynn running on this instance type.
