### ISSUE TITLE
flynn mysql dump outputs extra line feeds, breaking the dump

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#3573]
12:00 < rikurr_> Hello again. Finally a bug to report: the output of `flynn mysql dump` has extra new lines in it which breaks restoring from the dumps
12:01 < rikurr_> example:
12:01 < rikurr_>  ... ,NULL,NULL,0),(53,'user',5,'user_avatar','test_profile.png',N
12:01 < rikurr_> ULL,108530,64,64,'image/png','https://SNIP','2016-09-21 19:04:49',1,NULL,NULL,0), ...
12:02 < rikurr_> I get an error for the ,N\nULL part
12:04 < rikurr_> if it helps, it seems to me that lines longer than 10k characters are broken apart by adding the extra new line at every 10k character count.
12:04 < rikurr_> exactly 10k characters

**Comment by lmars** [comment]
The issue here is that container output is buffered into syslog messages of max 10k bytes (see [here](https://github.com/flynn/flynn/blob/master/host/logmux/logmux.go#L345)), and then streaming those messages inserts a newline between them [here](https://github.com/flynn/flynn/blob/master/host/libcontainer_backend.go#L1112).

We should stop assuming that log messages are complete lines (perhaps put the newline in the message itself?).
