### ISSUE TITLE
Submodules resolution for buildpacks

### ISSUE THREAD

**Issue by FlorianRappl** [flynn/flynn#3611]
Steps to reproduce:

1. Create a new app that is based on a non-default recursive buildpack, i.e., a buildpack requiring submodules to be resolved (in my case this was the official CF [dotnet-core-buildpack](https://github.com/cloudfoundry/dotnet-core-buildpack) buildpack)
2. Add a `.buildpacks` file specifying the recursive buildpack
3. Push the app via `git push flynn master`
4. See the build failing once functionality from the submodules is required (in my case the `compile-extensions` have not been resolved; so `download_dependency` was missing)

I had to modify the buildpack to include the `compile-extensions` directly; as the submodule was not auto-included. This was sufficient to make the build run correctly.

Thanks for this awesome piece of software ❤️ - truly a wonderful project with a great architecture and mindset!

**Comment by lmars** [comment]
@FlorianRappl I assume you are creating a `.buildpacks` file which triggers Flynn to install the buildpacks using the [Heroku multi buildpack](https://github.com/heroku/heroku-buildpack-multi), which doesn't seem to do a recursive clone (see [here](https://github.com/heroku/heroku-buildpack-multi/blob/master/bin/compile)).

If you just need to use a single, custom buildpack then you can instead set the `BUILDPACK_URL` environment variable and then Flynn will clone the buildpack recursively (see [here](https://github.com/flynn/flynn/blob/master/slugbuilder/builder/install-buildpack#L33-L42)).

To demonstrate using [this example app](https://github.com/IBM-Bluemix/aspnet-core-helloworld):

Using `.buildpacks`:

```
$ cat .buildpacks 
https://github.com/cloudfoundry/dotnet-core-buildpack.git

$ git push flynn master                                                                                                                                           
...
-----> Building asp...
-----> Multipack app detected
       =====> Downloading Buildpack: https://github.com/cloudfoundry/dotnet-core-buildpack.git
       =====> Detected Framework: ASP.NET Core (buildpack-1.0.4)
...
       sh: 1: /tmp/buildpackqNdjw/compile-extensions/bin/download_dependency: not found
       FAILED: command failed, exit status 127
```

Using `BUILDPACK_URL`:

```
$ flynn env set BUILDPACK_URL="https://github.com/cloudfoundry/dotnet-core-buildpack.git"
Created release da358714-0b96-48d3-9696-c58c951e66a2.

$ git push flynn master
...
-----> Building asp...
-----> Fetching custom buildpack
-----> ASP.NET Core (buildpack-1.0.4) app detected
       ASP.NET Core buildpack version: 1.0.4
       ASP.NET Core buildpack starting compile
...
       ASP.NET Core buildpack is done creating the droplet
-----> Discovering process types
       Default process types for ASP.NET Core (buildpack-1.0.4) -> web
-----> Compiled slug size is 159M
-----> Creating release...
=====> Scaling initial release to web=1
-----> Waiting for initial web job to start...
=====> Initial web job started
=====> Application deployed
To https://git.1.localflynn.com/asp.git
 * [new branch]      master -> master
```

We can't open an issue on the Heroku multi buildpack because it is a fork and looks like [it is deprecated](https://github.com/heroku/heroku-buildpack-multi/pull/7), but we can try submitting a patch anyway.

**Comment by FlorianRappl** [comment]
Yes indeed I was going with a `.buildpacks` file (edited the steps to reproduce). From the documentation it sounded like both are the same (sorry for my confusion), so I went with the file as it seemed easier / more transparent to maintain.

**Comment by lmars** [comment]
@FlorianRappl I too was initially confused, it is unclear why the multi buildpack does not clone the submodules (likely just an oversight).

You can find the docs [here](https://github.com/flynn/flynn/blob/master/docs/content/apps.md#buildpacks) if you want to update them and send a pull request?

**Comment by titanous** [comment]
It looks like we should switch to this version of the multi buildpack: https://bitbucket.org/cf-utilities/cf-buildpack-multi

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
