### ISSUE TITLE
SSL bundle cert order reversed

### ISSUE THREAD

**Issue by kvitajakub** [flynn/flynn#3803]
Hello,

I was moving cluster to my domain and set up git with my SSL cert. Right now flynn requires certificates bundle in reverse order than what is usually expected and I had to reverse the certificates order. Is it possible to support same behavior as other tools?

Reference: [https://support.comodo.com/index.php?/Knowledgebase/Article/View/1145/0/how-do-i-make-my-own-bundle-file-from-crt-files](https://support.comodo.com/index.php?/Knowledgebase/Article/View/1145/0/how-do-i-make-my-own-bundle-file-from-crt-files)

Openssl order of certs in bundle:
```
# Intermediate CA Certificate
# Your SSL Certificate
```

Flynn order of certs in bundle:
```
# Your SSL Certificate
# Intermediate CA Certificate
```

How to verify if cert bundle is fine: `openssl verify domain-bundle.crt`

**Comment by titanous** [comment]
We use the same order that nginx and Apache use (which is the same order used in the TLS protocol [Certificate message](https://tools.ietf.org/html/rfc5246#section-7.4.2)).

https://nginx.org/en/docs/http/configuring_https_servers.html#chains
https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslcertificatefile

In the future we'll automatically build the chain so that there is no way to mess this up: #1251
