### ISSUE TITLE
1GB+ of errors printed during cluster restore

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#3861]
22:15 < rikurr> so while doing a cluster restore, I got: 16384\n(1 row)\n\n lowrite \n---------\n  outputted a bazillion times, followed by even more of nERROR:  current transaction is aborted, commands ignored until end of transaction block\n
22:16 < rikurr> enough to fill up about 1GB of ram due to unlimited scroll in iTerm

restore was done on latest flynn AMI:
flynn-v20170116.0-ubuntu-xenial-1484616458 (ami-69c27e09)

**Comment by rikur** [comment]
Restore never finished:
```
ID                                                STATE    CREATED         CONTROLLER APP  CONTROLLER TYPE  ERROR
ip172312669-9d7c47ef-8833-4898-8555-f5b20020e712  running  16 minutes ago  postgres        web
ip172312669-39a38c7c-70ac-4d28-97b9-d53140ad9f2f  running  16 minutes ago  flannel         app
ip172312669-db18146e-3e85-4d7a-89a7-e3c2c4c38074  running  16 minutes ago  discoverd       app```

No actitivity on the server anymore.

**Comment by lmars** [comment]
@rikur do you have the `DEBUG` environment variable set when you run `flynn-host bootstrap`? If you do, then that's why you get all the output (see [here](https://github.com/flynn/flynn/blob/master/host/cli/bootstrap.go#L495-L497)).

It sounds like the restore of the postgres database is failing, but it would be good to try and filter through the output and find the underlying error.

Another option is to assume this backup is corrupt and try making another one.

**Comment by rikur** [comment]
Hard to debug this anymore. Restore usually works like charm, but this time the source cluster was probably about five months behind in updates.. feel free to close.
