### ISSUE TITLE
flynn import fails

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#3862]
```
23:06 < rikurr> importing fails:
23:06 < rikurr> 157.55 MB / 157.55 MB [========================================] 100.00 % 17.03 MB/s 9s
23:06 < rikurr> error uploading slug: remote job exited with status 2
```

My theory: exported apps don't include BUILDPACK_URL if it' the default one. When I restore from an older flynn to a new one, the buildpacks have been bumped and the build might fail.

To mitigate, I will make sure that I have "engine" defined in package.json for my node apps.

Let me know if you think that exporting with a BUILDPACK_URL is a good idea or not. Could be an option during importing like routes are.

**Comment by josephglanville** [comment]
While that is an interesting idea an exported app should fail to import if the buildpacks have been updated because a build shouldn't run on import, it should simply deploy the current slug.

The fact the slug is large shouldn't be a problem either as it should be converted to a squashfs layer.

If this is reproducible could you capture cluster logs with `flynn-host collect-debug-info` after reproducing so we can check out at which point it fails?

**Comment by rikur** [comment]
It was caused by the new limitations imposed by squashfs.

`flynn -a app limit set slugbuilder temp_disk=1G` fixed the issue.

**Comment by rikur** [comment]
Please feel free to close this issue
