### ISSUE TITLE
docker permission denied

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#3997]
When I try to

`flynn docker login
`
I get
`error running `docker login`: exit status 1 - output: {"Flag --email has been deprecated, will be removed in 1.14.\nWarning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/info: dial unix /var/run/docker.sock: connect: permission denied). Using system default: https://index.docker.io/v1/\nGot permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/auth: dial unix /var/run/docker.sock: connect: permission denied\n" '\x00' "\x00\x00\x00\x00" "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" '\x00'}`

I could reproduce this on amazon and digitaalocean when creating a new cluster, doing set-url and login on flynn docker.

What am I doing wrong?

**Comment by lmars** [comment]
@grauschnabel are you running the `docker` daemon?

You will need to set `DOCKER_HOST` if you are running Docker in a non-standard way (i.e. it isn't running locally listening on the `/var/run/docker.sock` socket).

**Comment by lmars** [comment]
P.S. a good check is that you can successfully run `docker info`.

**Comment by grauschnabel** [comment]
i just thought, flynn would run the daemon itself, if I use the installer which creates the droplet for me, so there would be no need to take a hand on.

That's why I created a new droplet just for testing, to have it clear, ... Is this a bug?

**Comment by lmars** [comment]
@grauschnabel the Flynn installer is all about installing Flynn on remote hosts (e.g. DigitalOcean droplets), which you can then deploy to by either `git push` or `flynn docker push`, usually from other machines (e.g. your local machine).

If you want to use the droplet to both run Flynn and as the machine you want to push Docker images from, you will need to install Docker on the droplet (see [here](https://docs.docker.com/engine/installation/linux/ubuntu/)).

**Comment by grauschnabel** [comment]
I'm now not really sure if I understand this correctly, after installing flynn git push works fine but flynn docker push doesn't, because I have to configure the target machine for docker by hand but the other things work fine?

**Comment by lmars** [comment]
@grauschnabel

> after installing flynn git push works fine but flynn docker push doesn't

`git push` works fine because you already have git installed and so the installer can automatically configure it to be able to push to the cluster, then when you run `flynn create` in a git repository, Flynn can detect it is a git repository and add a git remote for you.

Similarly, if you want `flynn docker push` to work then you need to have Docker installed (which you will use to either `docker pull` an image or `docker build` an image ready to be pushed to Flynn with `flynn docker push`). Docker however is more difficult to configure automatically (there is no API to make it trust a TLS certificate for example), hence why there are a few more steps in getting it configured.

See [here](https://docs.docker.com/engine/installation/) for instructions on how to install Docker if you want to use it.
