### ISSUE TITLE
Riak CS appliance

### ISSUE THREAD

**Issue by WriteCodeEveryday** [flynn/flynn#4040]
In regards to [this issue](https://github.com/flynn/flynn/issues/3145), is there a way we could consider adding the docker-riak-cs container as a "built-in datastore".

The idea would be to allow someone to one-click add the container to an app, then flynn mounts the necessary keys (AWS_SECRET, AWS_ID), and allows for bucket creation from an ENV variable on the container itself.

This would remove the external S3 dependency for projects while still allowing S3 storage for usage within the Flynn cluster itself for those who need it.

The recommended setup is a [multi-node production version](https://github.com/hectcastro/docker-riak-cs) while there is a [single node testing version](https://github.com/ianbytchek/docker-riak-cs)

**Comment by lmars** [comment]
@WriteCodeEveryday I don't think `docker-riak-cs` will be made a built-in appliance because Flynn already has the built-in blobstore with pluggable backends (which now has a [minio backend](https://github.com/flynn/flynn/pull/4012) too). A Riak CS backend could make sense though.

There is of course no reason you can't just deploy `docker-riak-cs` as a normal app.

**Comment by WriteCodeEveryday** [comment]
I was really referring to putting in right next to Redis on the "Provision Database" menu?

The idea being you could spin up an S3 equivalent within Flynn itself (and put the ENV variables within the app like a miniature S3 for testing)

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
