### ISSUE TITLE
nodes fail to link but reports no issues

### ISSUE THREAD

**Issue by ChaosMTA** [flynn/flynn#4178]
I've followed the installation guide to a tee. The whole process reports no errors and I am able to get a login token for the dashboard and such. However, after the process is completed running `flynn cluster` returns no clusters in the list. Moreover, if I use the dashboard and attempt to deploy an app, it will crash during the launch process and be unable to reach the host anymore until I restart the server(in which it will crash the dashboard again)

The dashboard will time out everytime after clicking to launch an app.

**Comment by titanous** [comment]
What is the output of the `flynn cluster add` command?

**Comment by ChaosMTA** [comment]
```
root@flynn:~# flynn cluster add
usage: flynn cluster
       flynn cluster add [-f] [-d] [--git-url <giturl>] [--no-git] [--docker-push-url <url>] [--docker] [-p <tlspin>] <cluster-name> <domain> <key>
       flynn cluster remove <cluster-name>
       flynn cluster default [<cluster-name>]
       flynn cluster migrate-domain <domain>
       flynn cluster backup [--file <file>]
       flynn cluster log-sink
       flynn cluster log-sink add syslog [--use-ids] [--insecure] [--format <format>] <url> [<prefix>]
       flynn cluster log-sink remove <id>
root@flynn:~# flynn cluster
NAME  CONTROLLER URL  GIT URL  DOCKER URL
```

**Comment by titanous** [comment]
There should have been a command printed at the end of `flynn-host bootstrap`, starting with `flynn cluster add`, you'll need to run it for your cluster to be accessible from the CLI.

**Comment by ChaosMTA** [comment]
Sorry for the misunderstanding. That command completes properly and returns
`Cluster "default" added and set as default.`

and `flynn cluster` returns properly however,
After selecting an app from the dashboard it will freeze on "Launching" and the dashboard will stop responding.

Running on the CLI `flynn create example` will freeze and return nothing.

**Comment by lmars** [comment]
@ChaosMTA do all of your nodes have the same hostname? Flynn uses the hostname as the host ID, so they should be distinct (hostnames in general are expected to be distinct).

**Comment by ChaosMTA** [comment]
Sorry if I'm misunderstanding @lmars but I thought that's how it should be configured? The docs show all of them having the same domain just seperate A records for DNS round robin high availability.

**Comment by ChaosMTA** [comment]
I was able to get it working doing that. It wasn't clear in the documentation.

Regarding this though when I run `flynn-host ps` I can see my app running on one of my nodes but not the others. Shouldn't it be running on all of them in case one goes down? Or do I need to scale the web processes from 1 to three?

**Comment by lmars** [comment]
> The docs show all of them having the same domain just seperate A records for DNS round robin high availability.

The docs show that the cluster domain (for example `demo.localflynn.com`) should have A records pointing at the IP address of each of the nodes in your cluster (e.g. `192.168.84.42`, `192.168.84.42`, etc.), and that you should also have a wildcard CNAME record pointing at the cluster domain (i.e. `*.demo.localflynn.com CNAME demo.localflynn.com`).

The hostnames you choose for your nodes is completely separate to this configuration. You are free to configure whatever hostnames you want (e.g. `1.example.com`, `2.example.com` etc.), Flynn just expects them to be different (which is a valid expectation, multiple hosts on the same subnet should generally not be given the same hostname).

> Regarding this though when I run flynn-host ps I can see my app running on one of my nodes but not the others. Shouldn't it be running on all of them in case one goes down? Or do I need to scale the web processes from 1 to three?

Flynn will schedule app jobs as evenly as possible across the cluster, but if you only set the scale to 1, then it will only run a single job on one host (because that is the configured scale). If you want more than one job running in the cluster then you should scale it up. Also note that if the host running that single job goes down, Flynn will schedule the job on another healthy host, thus maintaining the desired scale of running a single job in the cluster.

**Comment by ChaosMTA** [comment]
Thank you for the clarification!
