### ISSUE TITLE
Command to drain node gracefully

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#432]
There should be a command that allows a node to be removed from the cluster without dropping requests or causing availability issues for any services on the cluster.

**Comment by abagshaw** [comment]
Just wondering if this is handled by demoting a node? https://flynn.io/docs/production#replacing-hosts

**Comment by josephglanville** [comment]
@abagshaw demotion is definitely part of it. A member of the cluster acting as a Raft peer should definitely be demoted (and a new node promoted to take it's place etc) before it is replaced.

**Comment by lmars** [comment]
To clarify, I think draining a node will consist of:

* mark the terminating host as shutdown
* stop user app jobs (if this is a cluster scale down event, then scale down the user apps, otherwise move them to other hosts)
* move non-omni system jobs to other hosts (perhaps checking cluster status along the way)
* demote discoverd
* stop flynn-host

This would probably be handled by a controller background job.

**Comment by lmars** [comment]
Probably want a configurable router drain timeout for the user apps too (#3513).

**Comment by abagshaw** [comment]
Another potential issue - if I understand it correctly, each Flynn node does it's own load balancing and can either handle an incoming request or proxy it to another node - but the issue is because each Flynn node has it's own A record in the DNS, when gracefully shutting a node down it's possible that a client that has cached DNS records sends a request to that recently removed node and doesn't get a response (I'm assuming the client would then try a different A record and the request would succeed...but I still don't like the idea of requests going out to non-existent nodes).

**Comment by lmars** [comment]
@abagshaw that is indeed an issue but not something Flynn itself can manage, you would have to co-ordinate with your DNS provider to make sure the A record is removed, or alternatively have a load balancer in front of your Flynn cluster which can stop routing requests to the terminating node (e.g. HAProxy / AWS ELB etc.).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
