### ISSUE TITLE
Question: running multiple jobs of clock (cron)

### ISSUE THREAD

**Issue by zulhfreelancer** [flynn/flynn#4324]
Hi,

I'm reading your Ruby [docs](https://flynn.io/docs/languages/ruby#clock) on how to do cronjob. If I have multiple instances of `clock` jobs running using `flynn scale clock=2` command, does it mean that each of my cronjob will get executed twice at the same time?

Thank you.

**Comment by lmars** [comment]
Running `flynn scale clock=2` means Flynn will ensure there is always two `clock` jobs running in the cluster, so if they both execute on the same schedule then each task will be executed twice, once by each job.

I suspect you want to just run `flynn scale clock=1` so that Flynn maintains a single `clock` job.

**Comment by zulhfreelancer** [comment]
Well noted. Thank you very much.
