### ISSUE TITLE
flynn docker login & bitbucket pipeline

### ISSUE THREAD

**Issue by martunta** [flynn/flynn#4388]
when doing flynn docker login I get
```
+ flynn docker login
Error configuring docker, follow the above instructions and try again.
WARN: docker configuration failed with a TLS error.
WARN:
WARN: Copy the TLS CA certificate /root/.flynn/ca-certs/default.pem
WARN: to /etc/docker/certs.d/docker.prod.creatomus.com/ca.crt
WARN: on the docker daemon's host and restart docker.
WARN:
WARN: If using Docker for Mac, go to Docker -> Preferences
WARN: -> Advanced, add "docker.prod.creatomus.com" as an
WARN: Insecure Registry and hit "Apply & Restart".
```

on my computer I can resolve that by following suggested steps. But when running it from CI environment, within bitbucket pipelines, I have not yet found a way how to do it. I copy the files as suggested, but I am not allowed to restart docker there. And docker is also provided as a service, so probably file copying is not even helpful. 

is there any other way how to link flynn and docker together, without exchanging certificates? maybe there is some flags or arguments to pass that could replace certificate copy? I could not find any in documentation

**Comment by lmars** [comment]
@martunta the best option is to use a CA issued certificate with the `docker-receive` app (rather than the default self-signed certificate):

* get the current route for the `docker-receive` app:

```
$ flynn -a docker-receive route
ROUTE                          SERVICE         ID                                         STICKY  LEADER  PATH
https:docker.example.com       docker-receive  http/69e8a5e5-06bf-4ad6-8daf-2aad7ebc8fac  false   false   /
```

* update the route:

```
$ flynn -a docker-receive route update http/69e8a5e5-06bf-4ad6-8daf-2aad7ebc8fac -s docker-receive -c "$(cat path/to/cert)" -k "$(cat path/to/key)"
```

You can get a free certificate from [Let's Encrypt](https://letsencrypt.org/) (which Flynn will [support natively soon](https://github.com/flynn/flynn/issues/1995)).

**Comment by martunta** [comment]
ok. 
on my local machine I did
```
*build my app*
docker build -t my-image .
flynn docker set-push-url
cp /home/name/.flynn/ca-certs/default.pem /etc/docker/certs.d/my-app/ca.crt
*restart docker*
flynn docker login
flynn -a my-app docker push my-image:latest
flynn -a my-app scale app=0 #I am not sure how else to restart it
flynn -a my-app scale app=1  
```
on CI platform (bitbucket pipelines) restarting docker and copying of certs was not possible, due to docker service being out of reach.

So, how do I replace `flynn docker push` with using `docker-receive` directly? 

I guess that I do the cert update for docker-receive only once outside of CI, and then use the cert everytime when CI process runs? is there parameter for `flynn docker push` where I can attach certificate?

thanks a lot for your help! This feels like odd corner I have got myself into, I really hope there is a way out.

**Comment by lmars** [comment]
@martunta sorry, perhaps I wasn't clear.

So the reason you have to do this copying of certificates is because the Docker registry that exists inside the Flynn cluster (which receives the Docker image when you run `flynn docker push`) uses a self-signed certificate (one that is generated when you start the cluster).

If you update the Docker registry in the Flynn cluster to use a CA issued certificate (i.e. one that will be trusted by BitBucket as a valid certificate), then there is no need to do any copying of certificates in CI.

So, doing the following should make CI work for you:

* acquire a valid certificate for your Docker domain `docker.prod.creatomus.com` (e.g. use [certbot](https://certbot.eff.org/docs/using.html#manual) to get one from Let's Encrypt)
* update the route for the Docker registry app to use your acquired certificates (using my instructions above)

**Comment by martunta** [comment]
ok, command you gave me did not work, it was just cat'ing cert contents to the console.
```
$ flynn -a docker-receive route update http/69e8a5e5-06bf-4ad6-8daf-2aad7ebc8fac -s docker-receive -c "$(cat path/to/cert)" -k "$(cat path/to/key)"
```
so I changed it to 

```
$ flynn -a docker-receive route update http/69e8a5e5-06bf-4ad6-8daf-2aad7ebc8fac -s docker-receive -c path/to/cert -k path/to/key
```
and now it finally worked out perfectly. 
(could have been dependant on unix flavor? I am using Ubuntu 18.04, does not matter!)

and now docker-receiver domain is secured with letsencrypt, and now bitbucket pipeline finally did not give the same error anymore on `flynn -a my-app docker push my-image:latest` in fact it did not give any error message. But somehow build was reported as failed. 

~~~ couple minutes of debugging ~~~

turns out that I need to do 'flynn docker login' after all. Now push completed.
and failed on timeout when doing scale app=0 odd. lets try again.

~~~ one more try ~~~
success!

thanks a lot, without you @lmars I would have gotten stuck and completely discauraged. Thanks once more!

**Comment by lmars** [comment]
@martunta ah yes, sorry, the `flynn route update` command was wrong, it should just be the path to the cert and key like you say, not the cert and key contents.

Glad you got it working!
