### ISSUE TITLE
it's been months since last stable release

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#4397]
there are releases in github but the last stable release is for v20170719.0

did you just not update https://releases.flynn.io/ or there were no stable release since then?

**Comment by philiplb** [comment]
https://github.com/flynn/flynn/issues/4319

**Comment by hadifarnoud** [comment]
I wish we could contribute more to help the core team. Flynn is awesome but didn't get the attention it needed. maybe spreading the word helps?

**Comment by artemave** [comment]
In the meantime, you can use `nightly` channel when creating cluster https://flynn.io/docs/installation/manual#installation

**Comment by philiplb** [comment]
Yep, but I don't want to use a nightly in production.

**Comment by titanous** [comment]
The nightly channel will soon be the only release channel, it's what we run in production, which is why the stable channel hasn't been bumped recently.

**Comment by philiplb** [comment]
Will the development model stay the same? So each merged change ends up in the nightly channel? Would that mean that we have to test before upgrade and have to decide what nightly to Install and what to skip?

**Comment by titanous** [comment]
The development model will stay the same. Testing in your specific environment before deploying to production is suggested. The "stable" channel ended up just being a monthly snapshot, since we run nightly internally no extra QA/testing was done. You could accomplish the same thing by picking one nightly a month to be your "stable" release.

**Comment by philiplb** [comment]
@titanous Understood, thank you.
