### ISSUE TITLE
Using external database

### ISSUE THREAD

**Issue by lautarocastillo** [flynn/flynn#4453]
Hi guys! I'm using Flynn for my app made in Ruby on Rails, and I would like to use an external DB hosted on AWS RDS.
I tried defining a env variable called URL, but it is not working...
Any ideas?

**Comment by parrolabs** [comment]
Can you provide a little bit more details? What are your ENV variables? Have you set the RDS database to allow public access ? It might be the security group. I would say, try public access and then later set a security group with more restrictions. I would say the security is your blocker.

**Comment by lautarocastillo** [comment]
@parrolabs thanks for your answer.
I have just one ENV named “url” and my db config for “production” environment is url: <=% ENV['URL'] %>.
On development and Heroku works that way, that’s why I’m a little bit confused

**Comment by parrolabs** [comment]
Hi @lautarocastillo,

I think the issue is that you need to enter a couple more ENV variables. Like e.g. RDS_HOST, RDS_PORT, RDS_USER, RDS_PASSWORD (please check the actual ENV that you have. That is necessary to connect to the RDS server. I think you need to review your ENV as that might be the issue. In Rails you can just set all those to an ENV and then look into RDS. 

Seems to be more an issue with RDS than with Flynn, though you should set all of those in Flynn ofcourse.

**Comment by parrolabs** [comment]
@lautarocastillo - Should we close this?

**Comment by lautarocastillo** [comment]
CLOSED
The solution was replacing this ENV variables
![screenshot from 2018-10-18 14-40-15](https://user-images.githubusercontent.com/18515893/47173187-ccca0180-d2e3-11e8-8a2b-1fd99efc1b00.png)
with RDS credentials.
@parrolabs thanks for your help!
