### ISSUE TITLE
Volume management

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#534]
We should add a volume management API and database (boltdb) to the host service. This will allow us to do things like restart without losing things like the etcd state, as well as manage database appliances.

Here's a rough outline of the features:

- create volume (w/quota + other metadata)
- start job with volume
- snapshot volume
- pull (and/or push) snapshot from host
- delete volume

The volumes may be backed by plugins so that we can use filesystems like zfs and btrfs.

The use cases for this are:

- Saving data from stateful services
- Taking backups of data
- Taking fast clones (via snapshots) of data to be used in db replicas
- Transfering snapshots between hosts for db replicas and other uses

**Comment by heavenlyhash** [comment]
Closed by #924

**Comment by onnimonni** [comment]
The issue description doesn't tell if flynn supports docker volumes or not. If I use in my Dockerfile will the created image work correctly in flynn eg. does it preserve the contents of the volume for the next deploy?

For example
```
VOLUME /tmp/
```

**Comment by lmars** [comment]
@onnimonni the `VOLUME` directive from a Dockerfile currently has no effect when the resulting image is pushed to Flynn (only `CMD`, `ENTRYPOINT` and `ENV` are used to configure `release.Args` and `release.Env`).

You can attach a volume to jobs by setting `"data": true` for a given process type in a release (and update the release with `flynn release update`), e.g.:


```json
{
  "processes": {
    "app": {
      "args": ["bin/app"],
      "data": true
    }
  }
}
```

This will then attach a volume at `/data`, which will persist on disk but will not be re-attached to any other jobs. Work is in progress to support re-attaching volumes to new jobs (see #2438), but given the distributed nature of Flynn and the fact that we do zero-downtime deploys (i.e. start new jobs before killing old ones), it is not all that straight forward to make volumes consistently available to all your jobs.

Another bit of work on the roadmap is supporting NFS shares (#1521) which would allow you to share files between jobs (either a directory from one of your hosts shared across the cluster or a service like [Amazon EFS](https://aws.amazon.com/efs/)).

**Comment by onnimonni** [comment]
Thanks!

My use case is that I want to store files in the volume just for caching. So atm when I deploy new version of the server all of the files in the cache will get wiped and my application will be a bit slower for a while. This is a good thing and also a bad thing depending of the situation.

I can bypass this limitation in few applications by using redis instead of files but I can't do this for all of my applications without huge rewriting.

But in this case It doesn't matter for me if the process dies and the worker is then relocated into another host without the same data in mounted volume.

So for this case I would want to have semi-persistant files and I can understand that it won't be high priority for flynn.
