### ISSUE TITLE
[question] Question about container

### ISSUE THREAD

**Issue by zhouyuzhe88** [flynn/flynn#937]
Hello!
Which container does flynn use now, Docker or libvirt-lxc?
After I use "vargrant ssh" get in to the VM, how can I see the content of a container?
Thanks.

**Comment by titanous** [comment]
libvirt-lxc. What do you mean by "see the content of a container"?

**Comment by zhouyuzhe88** [comment]
1. So all the services are running in the lxc container instead of Docker container? That means I can't use `--link` or `volumes` in Flynn?
2. How to enter into the container setup by Flynn? (e.g. we can use `nsenter` to get into the Docker namespace)

**Comment by zhouyuzhe88** [comment]
@titanous

**Comment by zhouyuzhe88** [comment]
So all the services are running in the lxc container instead of Docker container? That means I can't use --link or volumes in Flynn?
How to enter into the container setup by Flynn? (e.g. we can use nsenter to get into the Docker namespace)

**Comment by lmars** [comment]
@zhouyuzhe88 

> So all the services are running in the lxc container instead of Docker container?

That is correct, we use the libvirt LXC driver to run containers.

> That means I can't use --link or volumes in Flynn?

Rather than using `--link`, you can use the service discovery daemon which exposes a HTTP API and DNS server to all containers for registering and finding services.

For example, a Redis container can register itself with the name `redis` and other containers can access it using the hostname `redis.discoverd`.

Flynn does have the concept of volumes, but they are not currently exposed in an easy to use way. Work is ongoing on a volume management API (see #534).

> How to enter into the container setup by Flynn? (e.g. we can use nsenter to get into the Docker namespace)

`nsenter` is a utility for running processes in namespaces (see [the man page](http://man7.org/linux/man-pages/man1/nsenter.1.html)), so whilst I have not tried it myself, you should be able to use it with containers started by libvirt-lxc in the same way you do with Docker containers.
