### ISSUE TITLE
App-wide logs

### ISSUE THREAD

**Issue by archSeer** [flynn/flynn#98]
Application-wide logs, returning a combined log stream of all app containers. Would simplify this usecase:
```
$ flynn log router
controller: not found
$ flynn -a router ps
e5eee5d32f1345ebb6c4de6220fc433f
$ flynn log e5eee5d32f1345ebb6c4de6220fc433f
...
```
This would simply become `flynn log router`

**Comment by titanous** [comment]
@benburkert and @bgentry are working on this.

The current plan is to replace logbuf with a logmux package that can buffer and ship logs to the aggregator. In order to keep the ability to debug when layer 1 (containing the aggregator) isn't running, we need to be able to get the recent logs of all jobs on a host. A couple options here (not all exclusive):

- If layer 0 bootstrap fails, all logs could be dumped to flynn-host stdout or a log file
- If a debug flag is specified, all logs could be streamed to flynn-host stdout or a log file

The main goal is to make sure we always have access to logs when things are broken, without too much overhead in flynn-host/logmux to support it.

The interactive attach endpoint will stick around, so we can have layer 1 bootstrap do an interactive run of any jobs it starts pre-aggregator and dump those logs if things fail.
